### ISSUE TITLE
Web site fails on ios safari

### ISSUE THREAD

**Issue by gedw99** [cogentcore/core#1005]
### Describe the bug

Main cogent core web site fails in iOS Safari .

it reloads when you try to do certain basic things …

### How to reproduce

If you have IOS mobile, just click the link the web site 

if not then use browser stack which has real iOS hardware for free that you access via their web gui . 

### Platform

iOS

**Comment by kkoreilly** [comment]
Thank you for reporting this! I can reproduce this and will work on fixing it immediately. The reason why it says 0.2.1 is that it uses the next version after the latest release (so 0.2.0 becomes 0.2.1) for the pseudo versions after it.

**Comment by kkoreilly** [comment]
Note that you may need to clear your cache to get this to work; see https://support.apple.com/en-us/105082.

**Comment by kkoreilly** [comment]
Also note that the horizontal scrolling issues with the website on mobile should be resolved soon.

**Comment by kkoreilly** [comment]
Great!
