### ISSUE TITLE
IOS Mobile Safari - Pickers also open Keyboard

### ISSUE THREAD

**Issue by gedw99** [cogentcore/core#1006]
### Describe the bug

Scope IOS Safari. Not sure is Android does the same.

Cant get to the Pickers because the keyboard opens.

![2024-07-11 17 23 17](https://github.com/cogentcore/core/assets/53147028/0f35d08c-34b0-48e3-a565-1beb5a739cc6)

### How to reproduce

On IOS Safari go to:

https://www.cogentcore.org/core/widgets/pickers/time-pickers

### Platform

iOS

**Comment by kkoreilly** [comment]
Thanks for reporting this! I think this is a duplicate of #764, which I will fix in the coming days before our initial release.

**Comment by kkoreilly** [comment]
I fixed this issue in d2cfe75cee20c5a5474956a1a52c3a798c243521, and I will work on improving the speed of the layout updating on virtual keyboard changing soon as well.
