### ISSUE TITLE
Performant video playback support 

### ISSUE THREAD

**Issue by c1ngular** [cogentcore/core#1044]
### Describe the feature

introduce hardware decoding support, zero -copy fashion to boost the performance.

or maybe switch to new implementations such as libvlc or libmpv which already has it on many different platforms and hardwares ?

by the way, congratulations and great job on initial release .

**Comment by kkoreilly** [comment]
Yes, improving our video support will be a key part of the v0.4 release.

**Comment by c1ngular** [comment]
i would also suggest a onframe event on video widget, so we could have decoded frame info and actual image data for future tasks such as object detection/recognition etc ... make its api as flexible/more as possible, leave the space for more potential use cases . 

thanks

**Comment by kkoreilly** [comment]
Yep, we will improve the video API as part of our video support improvements. Thanks for the idea!

**Comment by rcoreilly** [comment]
#516 is the original issue on this topic
