### ISSUE TITLE
Improve app bar

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#1074]
### Describe the feature

There is room for improvement with our current app bar. Here are some things we should consider:

* Disable the back button when it is not relevant
* Improve the app chooser styling
* Possibly center the app chooser or move it to a button in the overflow menu (maybe only on mobile)
* Move it into the system title bar area
* Support contextual app bars that focus more on the title / other info than a big search bar
* Add the app and/or user icon
* Add an option to disable the app bar (#1072)

If anyone else has ideas or feedback here, that would be helpful.

**Comment by runrc** [comment]
It might be useful to add documentation to explain what the app bar is, what useful functionality it offers, and how to use it.

**Comment by kkoreilly** [comment]
Yes, regardless of what changes we make, we will clearly document the result. Thank you for the feedback!

**Comment by kkoreilly** [comment]
I completed a major refactoring of our approach to this area, so this issue is resolved; see #1197 for more information.
