### ISSUE TITLE
Table column headers are misaligned

### ISSUE THREAD

**Issue by runrc** [cogentcore/core#1077]
### Describe the bug

There are a number of cosmetic issues with the table column headers,

- When a table is created the column headers are shifted slightly to the right. They are not correctly aligned with the table columns.
- When the first column header is clicked to enable sorting the header is expanded to show the direction of sort graphic, this in turn expands the whole column horizontally which is annoying. It would ideal to pre-allocate space for the sorting icon so the column header and its text doesn't jump about.

### How to reproduce

Create a simple table and click on the first column header.

### Platform

macOS

**Comment by kkoreilly** [comment]
Yes, we will definitely fix this; it should just be a simple layout bug. Thank you for reporting this!

**Comment by rcoreilly** [comment]
I'm not so sure about that: when we have a lot of columns, reserving extra space for the sorting thing can take up a lot of extra room..

**Comment by runrc** [comment]
> I'm not so sure about that: when we have a lot of columns, reserving extra space for the sorting thing can take up a lot of extra room..

This should really be decided by the user, since they will know how best to display their own data, rather than being forced by the framework.

I don't think there will be much extra space taken up as there will be padding on the right (or left) of the column header text.
For example, see how [Tabulator](https://tabulator.info) does it.
Perhaps giving the user a choice of where and how to show the sorting direction would be useful?
Or, allow the user to specify a styler for a column header?

**Comment by kkoreilly** [comment]
I strongly disagree with @rcoreilly; it really should take almost no space to reserve the sorting button, especially given that data typically takes up more space than the header anyway. I will work on implementing that now.

**Comment by kkoreilly** [comment]
@runrc, I filed #1078, which is still a WIP, but it fixes your second issue, so things no longer shift around when you start sorting something. I can definitely see your first issue, and I will work on fixing it now. Another question is whether we want the sorting indicator, which is now to the right of the name as is more standard, to be all the way at the end of the column header, or right next to the name as it is now.

**Comment by kkoreilly** [comment]
I also just fixed your first issue; everything should be aligned properly now. The only remaining question is whether the table sort indicator should be placed at the far end of the column header.

**Comment by runrc** [comment]
OK great. The position of the column header sort indicator depends on the alignment of the column header text. However, for consistency I think it should be shown after the column header text. So even, if the column header text is left, middle or right justified the indicator should be shown right next to the text. Although perhaps this could be configurable?

**Comment by kkoreilly** [comment]
Okay, I will keep it always right after the header text. You can configure the alignment using our existing styler and maker functionality, but I recognize that this is a suboptimal solution:

```go
	tree.AddChildInit(tb, "header", func(w *core.Frame) {
		w.Maker(func(p *tree.Plan) {
			for _, item := range p.Children {
				if item.Name == "_head-index" {
					continue
				}
				tree.AddInit(p, item.Name, func(w *core.Button) {
					w.Styler(func(s *styles.Style) {
						s.Justify.Content = styles.Center
					})
				})
			}
		})
	})
```

Therefore, if you or anyone else does actually need to have it aligned differently, I would be happy explore adding an easier API for that.
