### ISSUE TITLE
Text Input Validator Tooltip Misbehaves with Keyboard Commit

### ISSUE THREAD

**Issue by davecgh** [cogentcore/core#1085]
### Describe the bug

A text field with a validator defined permanently shows the tooltip with the validation error when you commit a value by hitting ctrl/command+enter.  Resolving the validation error and committing the new text does not clear the tooltip.

However, mousing over the text field will clear the tooltip.

### How to reproduce

1. Go to the documentation page for text fields: https://www.cogentcore.org/core/widgets/inputs/text-fields
2. Enter something like "Test" in the example text field that specifies a Validator to ensure the string contains "Go"
3. Ensure the mouse cursor is _NOT_  hovering the text field
4. Hit ctrl+enter (or command+enter on Mac) to commit the text that will fail validation
5. Observe the validation error tooltip with "Must contain Go" is displayed as expected, however it never goes away
6. Update the text to "Test Go" so that it no longer fails validation and hit ctrl+enter (or command+enter on Mac) to commit it
7. Observe the validation error tooltip is still visible.
8. Move the mouse cursor over the text field and observe the tooltip is cleared

### Example code

```go
tf := core.NewTextField(b)
tf.SetValidator(func() error {
	if !strings.Contains(tf.Text(), "Go") {
		return errors.New("Must contain Go")
	}
	return nil
})
```

### Platform

Web

**Comment by kkoreilly** [comment]
Thank you for reporting this and giving clear instructions on how to reproduce it! I can reproduce this and will work on fixing it.
