### ISSUE TITLE
Long press tooltip on slider does not update or disappear on value change

### ISSUE THREAD

**Issue by davecgh** [cogentcore/core#1086]
### Describe the bug

Long pressing on a slider to show the tooltip with the current value and then dragging the slider to change its value does not update the tooltip or remove it resulting in incorrect value display.

### How to reproduce

1. Go to the documentation page for tooltips: https://www.cogentcore.org/core/widgets/basic/tooltips
2. Long press on the slider to cause the tooltip with its current value to display and keep the button depressed
3. Drag the slider to change its value
4. Observe that the tooltip neither updates nor disappears

### Example code

```go
core.NewSlider(b)
```

### Platform

Web

**Comment by kkoreilly** [comment]
Thank you for reporting this; I can reproduce it. I will make it so that the tooltip disappears when you start dragging the slider.
