### ISSUE TITLE
Incorrect chooser behavior with autocomplete, validation, and keyboard commit

### ISSUE THREAD

**Issue by davecgh** [cogentcore/core#1087]
### Describe the bug

Committing an invalid value in an editable chooser via ctrl+enter (command+enter on Mac) results in autocomplete of the last selected option, but validation still claims to have failed.

### How to reproduce

1. Go to the documentation page for choosers: https://www.cogentcore.org/core/widgets/inputs/choosers
2. In the example editable chooser that demonstrates autocomplete and validation support choose the "Oldest" option
3. Select the text and change it to "Bogus" and then hit ctrl+enter (or command+enter on Mac) to commit the text that will fail validation
4. Observe that it autocompletes to "Oldest", but still displays the "unknown value" validation error icon
5. Click in the text field of the chooser and somewhere outside of it to observe the validation error is still present
6. Choose one of the options and observe all is now as expected

### Example code

```go
core.NewChooser(b).SetEditable(true).SetStrings("Newest", "Oldest", "Popular")
```

### Platform

Web

**Comment by kkoreilly** [comment]
Thank you for reporting this. I can reproduce this issue. I will change it to keep the text "Bogus" until you select a valid option.
