### ISSUE TITLE
Golang Weekly appearance (and an app candidate for serious proof that the framework rocks!)

### ISSUE THREAD

**Issue by kristofer** [cogentcore/core#1097]
### Describe the feature

One of the things I learned from working at NeXT, like 3+ years ago, was

 _let's make sure every library/framework has an app that shows the framework "workable"_

And

in the same issue of Golang Weekly as Cogent's appearance ( https://golangweekly.com/issues/517 ) was a link to this:

https://github.com/jmigpin/editor

And me, am wondering just how hard might it be to port this app to this framework :-); Any opinions??

**Comment by theclapp** [comment]
Check out all the apps under https://github.com/cogentcore/cogent, in particular, the IDE, Cogent Code, https://github.com/cogentcore/cogent/blob/main/code/README.md.

**Comment by kkoreilly** [comment]
Yes, as we state in the initial release blog post, there are various powerful apps built with the framework, including Cogent Code as @theclapp mentioned above (there is also a [web version](https://www.cogentcore.org/cogent/code/)), [Cogent Canvas](https://www.cogentcore.org/cogent/canvas/), and the [Emergent neural network models](https://www.emersim.org/).

**Comment by kristofer** [comment]
I see that, terrific!!

**Comment by fbaube** [comment]
> https://github.com/jmigpin/editor
> And me, am wondering just how hard might it be to port this app to this framework :-); Any opinions??

I'm wondering whether Cogent could co-exist with the Huma framework. Huma has the great idea that HTTP handlers are written by passing structs in & out, and the structs are auto- serialized & deserialized as JSON, and this whole scheme makes it possible to auto-generate documentation.

**Comment by kkoreilly** [comment]
Yes, it is very easy to create widgets from structs in Cogent Core (see [forms](https://www.cogentcore.org/core/widgets/collections/forms)), so it should be easy to make a GUI app based around something using Huma.
