### ISSUE TITLE
Android Vulkan doesn't work

### ISSUE THREAD

**Issue by SAXN-SYNX** [cogentcore/core#1101]
### Describe the bug

Compiled to apk using core pack android. Program installed fine but cannot run it.

### How to reproduce

download the demo, compiled to apk using core pack android. nearly 100 -150 mb apk file is made. Try to run in android

### Platform

Android

**Comment by kkoreilly** [comment]
Thank you for reporting this. Can you try using `core run android`? If that also doesn't work, can you provide more information about your Android device and its version?

**Comment by SAXN-SYNX** [comment]
core run android did succeeded with installation but app won't open in android phone.
Android Device : Samsung Galaxy M32
Android Version: 13
One UI Versioin: 5.1

**Comment by kkoreilly** [comment]
Thank you for the information. Please try running `core run android -d` and paste in the output here. Thank you!

**Comment by SAXN-SYNX** [comment]
[log] 
xcrun xcodebuild -version
adb logcat *:F Go:D GoLog:D
--------- beginning of main
08-04 15:03:54.027 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.027 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.027 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.027 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.028 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.028 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.028 25672 25768 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.063 25672 25672 I GoLog   : WARN android device reports unknown screen density density=450
08-04 15:03:54.152 25672 25774 I GoLog   : ERROR mkdir /data/data/Cogent Core: permission denied | cogentcore.org/core/system/driver/base.(*App).CogentCoreDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:141
08-04 15:03:54.475 25672 25672 I GoLog   : panic: vulkan error: vulkan error: initialization failed (-3)
08-04 15:03:54.475 25672 25672 I GoLog   : 
08-04 15:03:54.475 25672 25672 I GoLog   : ----- START OF STACK TRACE: -----
08-04 15:03:54.475 25672 25672 I GoLog   : goroutine 17 [running, locked to thread]:
08-04 15:03:54.475 25672 25672 I GoLog   : runtime/debug.Stack()
08-04 15:03:54.475 25672 25672 I GoLog   :      /usr/lib/go/src/runtime/debug/stack.go:24 +0x64
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/system.HandleRecoverBase({0x769b7ac9e0, 0x400278a360})
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/recover.go:50 +0x38
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/core.handleRecover({0x769b7ac9e0, 0x400278a360})
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/core/recover.go:33 +0x48
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/system/driver/android.(*App).SetSystemWindow.func1()
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/android/app.go:96 +0x34
08-04 15:03:54.475 25672 25672 I GoLog   : panic({0x769b7ac9e0?, 0x400278a360?})
08-04 15:03:54.475 25672 25672 I GoLog   :      /usr/lib/go/src/runtime/panic.go:770 +0x124
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/vgpu.IfPanic(...)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/vgpu/errors.go:39
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/vgpu.(*Pipeline).Config(0x4001af2100, 0xe0?)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/vgpu/pipeline.go:199 +0x4a0
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/vgpu.(*System).Config(0x4002796008)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/vgpu/system.go:283 +0x100
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/vgpu/vdraw.(*Drawer).ConfigSys(0x4002796008)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/vgpu/vdraw/config.go:106 +0x7bc
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/vgpu/vdraw.(*Drawer).ConfigSurface(0x4002796008, 0x4002780000, 0x4002780028?)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/vgpu/vdraw/vdraw.go:53 +0x9c
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/system/driver/android.(*App).SetSystemWindow(0x769c0dd460, 0x770b396810)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/android/app.go:116 +0x19c
08-04 15:03:54.475 25672 25672 I GoLog   : cogentcore.org/core/system/driver/android.onNativeWindowCreated(0x40001a7e01?, 0x769ae6ac9c?)
08-04 15:03:54.475 25672 25672 I GoLog   :      /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/android/android.go:144 +0xcc
08-04 15:03:54.475 25672 25672 I GoLog   : 
08-04 15:03:54.475 25672 25672 I GoLog   : ----- END OF STACK TRACE -----
08-04 15:03:54.475 25672 25672 I GoLog   : ERROR mkdir /data/data/Cogent Core Demo: permission denied | cogentcore.org/core/system/driver/base.(*App).AppDataDir /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/base/app.go:135
08-04 15:03:54.475 25672 25672 I GoLog   : ERROR mkdir /data/data/Cogent Core Demo: permission denied | cogentcore.org/core/system.HandleRecoverBase /home/zero/go/pkg/mod/cogentcore.org/core@v0.3.0/system/recover.go:60

**Comment by kkoreilly** [comment]
OK, thank you for giving me that log. The issue has to do with Vulkan, which we are about to get rid of in favor of WebGPU, which will fix this issue (see #507 and #1112), so this issue should be fixed within a few days.
