### ISSUE TITLE
Add a date input

### ISSUE THREAD

**Issue by j0hnsmith** [cogentcore/core#1120]
### Describe the feature

Similar to `core.TimeInput` but only renders a date field.

I couldn't find one but managed to get something that seems to work as expected with this code (copied from `core.TimeInput`. Also adds the ability to format the date (with a default, not sure if it's the best/correct way to set the default format).

Happy to create a PR, would it go in `timepicker.go`?

### Relevant code

```go
func NewDateInput(parent ...tree.Node) *DateInput { return tree.New[DateInput](parent...) }

// DateInput presents a text field for editing a date,
// which can pull up a [core.DatePicker] dialog.
type DateInput struct {
	core.Frame
	Time   time.Time
	Format string
}

func (ti *DateInput) WidgetValue() any { return &ti.Time }

func (ti *DateInput) SetFormat(f string) *DateInput {
	ti.Format = f
	return ti
}

func (ti *DateInput) Init() {
	ti.Frame.Init()

	if ti.Format == "" {
		ti.Format = "1/2/2006"
	}

	style := func(s *styles.Style) {
		s.Min.X.Em(8)
		s.Max.X.Em(10)
		if ti.IsReadOnly() { // must inherit abilities when read only for table
			s.Abilities = ti.Styles.Abilities
		}
	}

	tree.AddChild(ti, func(w *core.TextField) {
		w.SetTooltip("The date")
		w.SetLeadingIcon(icons.CalendarToday, func(e events.Event) {
			d := core.NewBody().AddTitle("Select date")
			dp := core.NewDatePicker(d).SetTime(ti.Time)
			d.AddBottomBar(func(parent core.Widget) {
				d.AddCancel(parent)
				d.AddOK(parent).OnClick(func(e events.Event) {
					ti.Time = dp.Time
					ti.UpdateChange()
				})
			})
			d.RunDialog(w)
		})
		w.Styler(style)
		w.Updater(func() {
			w.SetReadOnly(ti.IsReadOnly())
			w.SetText(ti.Time.Format(ti.Format))
		})
		w.SetValidator(func() error {
			d, err := time.Parse(ti.Format, w.Text())
			if err != nil {
				return err
			}
			// new date and old time
			ti.Time = time.Date(d.Year(), d.Month(), d.Day(), ti.Time.Hour(), ti.Time.Minute(), ti.Time.Second(), ti.Time.Nanosecond(), ti.Time.Location())
			ti.SendChange()
			return nil
		})
	})
}
```

**Comment by kkoreilly** [comment]
Thank you for filing this! What do you think about instead adding `ShowTime` and `ShowDate` bool fields to the existing `TimeInput` so that you can choose to only show one? That would reduce code duplication while achieving the same functionality. In terms of the date format, we probably want to add a user setting that can be set by default based on the user's language as part of internationalization (#9). Do you think that we should also add a widget field beyond that? Regardless, all of these seem like good possibilities, and I would be happy to accept a PR after we agree on a solution. (Also, for setting a default value, what you did would work, although you can also get rid of the if statement and just set it directly, since it will always be `""` in `Init`).

**Comment by j0hnsmith** [comment]
Good suggestions, I'll have a play to see what I can come up with. How about `HideTime/Date` modifier methods to leave the default behaviour intact?

My main motivation was to have a form that just displays a date input, I've had a dig but it seems like it's not possible. Would you be open to struct tags that hide date/time on `time.Time` fields on a form (using methods above)?

**Comment by kkoreilly** [comment]
If you add `ShowTime/Date` bool fields with default values of true (using the `Init` method as I described), it should preserve the current default behavior, and it is probably better to have a "positive" bool as opposed to a `Hide` one. I would be open to `time:"-" date:"-"` struct tags to hide the time/date; here is an example from `FileButton` that shows how to implement struct tags in general (for this, you could use `tags.Get` and directly compare the result to `"-"` and set `ShowTime/Date` to false if so). If you need any help, feel free to ask.

```go
func (fb *FileButton) OnBind(value any, tags reflect.StructTag) {
	if ext, ok := tags.Lookup("extension"); ok {
		fb.SetExtensions(ext)
	}
}
```

**Comment by kkoreilly** [comment]
(And actually `DisplayTime/Date` is probably more consistent with our other widgets. Then, you can make the struct tag `display:"time"` or `display:"date"` to display only that, which is also more consistent with our widely used `display:"-"`).

**Comment by j0hnsmith** [comment]
So I made a quick attempt but it wasn't successful as calling `core.NewTimeInput()` calls `TimeInput.Init()` immediately, there's no way to customise (eg setting `ti.ShowTime = false`) before `TimeInput.Init()` executes. 

I did try adding an `if ti.ShowTime {...` inside the `tree.AddChild()` callback but it rendered an empty `TextField` (I know it's not necessarily a nice solution was just playing around trying to get something to work).

Is there a way to customise that I'm missing? Any other suggestions?

I wonder if a solution based on multiple inputs, with the shared logic in unexported functions so there's no code duplication, would be acceptable, eg separate `DateInput`, `TimeInput` and renaming the existing `TimeInput` to `DateAndTimeInput`, api change isn't desirable though.

**Comment by kkoreilly** [comment]
Oh sorry I forgot that you need to put the logic inside a `Maker`. `tree.AddChild` is used for things without conditional logic, but you need to use a `Maker` and `tree.Add` for this, which allows you to check the conditionals each time in a closure instead of right in `Init`. So the basic structure is:

```go
func (ti *TimeInput) Init() {
...
ti.Maker(func(p *tree.Plan) {
  if ti.ShowDate {
    tree.Add(p, ...)
  }
  if ti.ShowTime {
    tree.Add(p, ...)
  }
})
}
```

Apologies again for forgetting that. If you have any further issues, please let me know. Thank you!

**Comment by j0hnsmith** [comment]
Thanks, turned out to be a simple change. I left out the formatting as that's a wider solution (also requires field size changes via styles).

**Comment by kkoreilly** [comment]
Thank you for filing the PR! I filed #1138 for the date format option.
