### ISSUE TITLE
Hiding app bar and removing margin from body

### ISSUE THREAD

**Issue by duggavo** [cogentcore/core#1127]
### Describe the feature

add a way to remove, or at least hide, the TopAppBar.

additionally, is it possible to completely remove the padding of the Scene?

**Comment by kkoreilly** [comment]
Yes, we are currently working on restructuring the app bar and adding an option to disable it (duplicate of #1074). To remove the padding of the Scene, you can do this:

```go
myWidget.Scene.Styler(func(s *styles.Style) {
  s.Padding.Zero()
})
```
