### ISSUE TITLE
Table - rows after 10,000 are misaligned

### ISSUE THREAD

**Issue by runrc** [cogentcore/core#1130]
### Describe the bug

When adding more than 10,000 rows to a table and scrolling the rows are misaligned and not rendered correctly.

### How to reproduce

Create the table with +10,000 rows and scroll down to row 10,000. 
The fields in the rows after 10,000 are not rendered as they should be.

<img width="1722" alt="Screenshot 2024-08-12 at 9 18 56 PM" src="https://github.com/user-attachments/assets/2247038c-e50b-47f3-9db4-c77f81b7618d">

### Example code

```go
type MyRow struct {
  Name   string
  Number int
}

rows := 20000
tableData := make([]*MyRow, 0, rows)
for row := range rows {
  tableData = append(tableData, &MyRow{Name: fmt.Sprintf("Row %d", row), Number: row})
}

b := core.NewBody("Test")
core.NewTable(b).SetSlice(&tableData).SetReadOnly(true)
```

### Platform

macOS

**Comment by kkoreilly** [comment]
I can reproduce this, and I realize what the issue is; we are specifying a precision level for the number values, but that should only affect digits after the decimal point, not digits before that.
