### ISSUE TITLE
Tab names need to be unique

### ISSUE THREAD

**Issue by runrc** [cogentcore/core#1131]
### Describe the feature

Currently, the name used for a tab must be unique, otherwise the selection of tabs with the same name is somewhat broken.
It would be useful to have the ability to name tabs with the same name. Alternatively, the documentation should be changed to emphasise that tab names are the identifier and must be unique.

**Comment by kkoreilly** [comment]
Yep, we have especially run into this issue with the new tab button, which makes tabs with the same names. I will work on implementing an automatic unique naming system for tabs soon.
