### ISSUE TITLE
Remove vgpu (Vulkan)

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#1134]
### Describe the feature

After we finish WebGPU support (#507 / #1112), we still need to remove `vgpu` and other Vulkan-related code later. We need to keep it for now since `gosl` relies on it and still needs to be rewritten around WGSL instead of HLSL.

Note that the continued presence of `vgpu` until that point will have no impacts on apps that do not use `gosl`.

**Comment by rcoreilly** [comment]
when removing vgpu, move to https://github.com/goki/vgpu

**Comment by kkoreilly** [comment]
(as an unmaintained reference for anyone using Vulkan, with an update and a link to our new WebGPU-based implementation).
