### ISSUE TITLE
time.Duration in a read only table isn't read only

### ISSUE THREAD

**Issue by j0hnsmith** [cogentcore/core#1141]
### Describe the bug

When a struct has a `time.Duration` field and is used in a read only table, the `DurationInput` isn't read only.

### How to reproduce

Run this code.

### Example code

```go
type SomeStruct struct {
    Took time.Duration
}
core.NewTable(b).SetSlice(&[]SomeStruct{{time.Duration(time.Minute)}, {time.Duration(time.Hour}).SetReadOnly(true)
```

### Platform

macOS

**Comment by kkoreilly** [comment]
Thank you for reporting this! I will fix this now.
