### ISSUE TITLE
text lineheight value did not have effect 

### ISSUE THREAD

**Issue by runsys** [cogentcore/core#1148]
### Describe the bug

set text lineheight but did not have effect.
version about 20240706
os freebsd 14.1
![屏幕截图 2024-08-18 213250](https://github.com/user-attachments/assets/43bda951-2182-442a-8182-c79b1cdefccd)

### How to reproduce

set text lineheight

### Platform

Linux

**Comment by kkoreilly** [comment]
Thank you for filing this. Apologies if I am incorrect, but it does look like it is having an effect; there is more vertical space around the line of text. You may want to also set the `s.Font.Size` property if you are trying to increase the size of the text. I confirmed that both properties are working. You can also try changing the `Type` to something larger like `TextHeadlineLarge` or `TextDisplayMedium`, which will change both the font size and line height for you.

**Comment by runsys** [comment]
I set s.Font.Size=units.Dp(48), now it showing are OK.
