### ISSUE TITLE
Button style font size did not have effect. how to set default font size for all.

### ISSUE THREAD

**Issue by runsys** [cogentcore/core#1150]
### Describe the bug

Button style font size did not have effect. how to set default font size by code for all. 
version about 20240706
os freebsd 14.1

### How to reproduce

see code in picture
![屏幕截图 2024-08-19 075046](https://github.com/user-attachments/assets/4b762675-0f7c-4b42-a9d2-329602f1e934)

### Platform

macOS

**Comment by kkoreilly** [comment]
You can use this code to set the font size of the button text:

```go
	bt := core.NewButton(b).SetText("Hello")
	tree.AddChildInit(bt, "text", func(w *core.Text) {
		w.Styler(func(s *styles.Style) {
			s.Font.Size.Dp(48)
			s.Text.LineHeight.Dp(48)
		})
	})
```

If you want to change the font size of all elements, you can change the `Font size` in the `Settings` menu.

**Comment by kkoreilly** [comment]
As of #1340, the font size of the text in a button is now automatically set to the font size of the button itself. The line height now automatically rescales based on the font size and thus does not need to be set. I will document those changes within a few days.
