### ISSUE TITLE
Suggestion on FileButton length after selection

### ISSUE THREAD

**Issue by DCowboy** [cogentcore/core#1177]
### Describe the feature

Currently, when a file is selected with a FileButton, the button displays the path in full. The longer the path, longer the button; and when it reaches the limit of a set frame or window the path is cut off at the end so that the user wouldn't be able to verify the correct file anyway.
It would provide more flexibility with space consideration to shrink that to something like:
mountpoint/.../filename.ext
/...filename.ext
filename.ext

For example: "C:/.../filename" or "home/.../filename" would help keep the button from expanding too far.  For the convenience of being able to double check the path, (which I assume is why the button currently displays the full path,) Perhaps changing the tooltip for the button to the full path could keep that convenience.

As an afterthought, perhaps adding an option for a character limit could also be beneficial from a front end design standpoint.

**Comment by kkoreilly** [comment]
Thank you for the suggestion! I agree with this idea; you can see that we do something similar for the `TreeButton` currently, using our `base/elide` package. I will implement this for the `FileButton`, with tooltips for both button types that show the full expanded path.

As a side note, it is possible to generically enforce a text length limit by setting `s.Max.X` in a `Styler` for a `Text` widget, but that is probably not the best way to implement something like this.

**Comment by DCowboy** [comment]
"As a side note, it is possible to generically enforce a text length limit by setting s.Max.X in a Styler for a Text widget, but that is probably not the best way to implement something like this."

Either that or a number for truncation of characters from the string. Either way alignment could still be be important in some cases, so I'd suggest either make it optional, or use right justification.

But again, a limit on text length was an afterthought on the idea that if someone can use long paths, others may use long filenames above 15 or 20 characters.

**Comment by kkoreilly** [comment]
Yes, my plan is to elide the text length to some number of characters (probably around 30) as we already do in `TreeButton`, which should not have any significant negative side effects.
