### ISSUE TITLE
Need an event for when a tab newly becomes visible, e.g., Show

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#1194]
### Describe the feature

@kkoreilly we have discussed this but I don't remember the current status.  In the emer sims, we really need to be able to get the current state of the Network when someone switches back to that tab.  Definitely do not want tab updating when not visible as it is expensive.

It would make sense for this to be the Show event, although there was some issue about whether Show is a "once" only event or not (could always use `sync.Once` to ensure where needed, presumably).

**Comment by kkoreilly** [comment]
With the new `NewTab` structure returning the `Tab` button, can't you just add an `OnClick` or `OnFinal` `events.Click` on that?

**Comment by rcoreilly** [comment]
alas, that does not work, for either straight OnClick or the OnFinal.  the tab does not come into view until after the click itself is processed by the tab button, and so it is still invisible when the Onclick events happened..

**Comment by kkoreilly** [comment]
`events.Show` events are now sent on tab changes as of #1337.
