### ISSUE TITLE
can't build video example (apple sonoma m3)

### ISSUE THREAD

**Issue by slukits** [cogentcore/core#1226]
### Describe the bug

```
~/go/src/github.com/core/examples/video[main]
$ go build
# github.com/cogentcore/reisen
../../../../../pkg/mod/github.com/cogentcore/reisen@v0.0.0-20240814194831-4d884b6e7666/audio.go:57:17: could not determine kind of name for C.swr_alloc_set_opts
```
### How to reproduce

see above

### Platform

macOS

**Comment by kkoreilly** [comment]
Have you done the installation instructions in [reisen](https://github.com/cogentcore/reisen)?

**Comment by slukits** [comment]
No, I didn't; sorry for the bother and thanks for the hint

**Comment by slukits** [comment]
No, I didn't; sorry for the bother and thanks for the hint
