### ISSUE TITLE
Cannot try cogentcore due to su password requirement

### ISSUE THREAD

**Issue by mark-summerfield** [cogentcore/core#1260]
### Describe the feature

When I tried `core setup` it would not let me proceed without me entering my su password. I am not willing to do that since I don't know what it would do to my system.

I always install Go locally, e.g., in `~/opt/go` with my packages in `~/opt/gopkg` so anything installed into Go doesn't need su access.

And as for third-party libs, e.g., OpenGL or whatever cogentcore uses, a simple list of what needs installing would allow me to do it myself.

PS having an executable called `core` on Unix does not make any sense; I suggest using a different name, `ccore` or pretty well anything else.

**Comment by kkoreilly** [comment]
Thank you for the feedback. It should print the command that it is trying to run in blue when you run `core setup`, so you can just copy that and run it directly.

If that doesn't work (or you are on Ubuntu which has multiple commands), you could also look at the source code, which has all of the commands it runs for each Linux distro / package manager, so you could copy the command for your distro and run it: https://github.com/cogentcore/core/blob/main/cmd/core/cmd/setup.go#L33

For the `core` executable name, do you know of any other executables that have a conflicting name? If there are no major other tools with conflicting names, I don't think it is worth renaming it. You can also locally alias it to `ccore` if you want.

**Comment by rcoreilly** [comment]
@kkoreilly it is the "core" dump files that cause the conflict -- I thought about that, but at least they aren't executable :)  And my sense is that this is typically turned off by default these days?

**Comment by mark-summerfield** [comment]
`core` files are still generated if you use traditional tools/langs, e.g., C and C++ with makefiles.

The command it shows in blue (I'm using Debian) is `sudo apt-get update`.

In the first place I wouldn't give it my password because even if it executes what it says it will execute I don't know what _else_ it will execute or do with my password.

And in the second place, that command will not work on my system because I don't use (and haven't installed) `sudo` on my Debian systems, for which I use `su`.

Go can easily be _locally_ installed wherever I like. Every other Go cmd and pkg works with this local installation, so I really don't see why cogentcore can't.

**Comment by kkoreilly** [comment]
Sorry, I meant Debian or Ubuntu for those that have multiple commands. As you can see in the source code I linked, you need to run:

```sh
sudo apt-get update
sudo apt-get install -f -y gcc libgl1-mesa-dev libegl1-mesa-dev mesa-vulkan-drivers xorg-dev
```

You can obviously substitute `su` for `sudo` in those commands.

That is all that `core setup` does on Debian. The reason why we have the `core setup` command is for convenience given that there are different installation steps for different operating systems and distros; in particular, the Windows installation steps are rather convoluted. Most people prefer that convenience and are not concerned about the password; this is open source software and thus it is easily verifiable that it does not do anything else with the password.

However, I can see where you are coming from, and if you think it would be helpful, I am open to listing the installation commands for Linux on a separate linked page such that people can run them manually if they wish.

**Comment by mark-summerfield** [comment]
I think Unix users would prefer to have the list of apt-get commands or simply the list of what needs installing.

I tried again but it seems that cogentcore relies on its own `core` program to build applications rather than relying on the `go` tool. I prefer to use the standard toolchain.

**Comment by kkoreilly** [comment]
Okay, I will add the list of commands on a linked page soon.

As stated on the [building page](https://www.cogentcore.org/core/setup/building), you can use the standard `go` tool whenever you want; the main point of the `core` tool is for mobile and web development, but it is completely optional otherwise.

Thank you again for your feedback!

**Comment by mark-summerfield** [comment]
I installed the Linux prerequisites and then tried the first "hello world" program using the `go` tool (I removed the `core` tool), which works fine. (Well, apart from the fact that when I click the button there is no visual feedback---it doesn't press in and then come back.) So now I'm working my way through the tutorial.

**Comment by kkoreilly** [comment]
Sounds good! There is a slight change in color when you press the button, but we can make that more emphasized at some point.

**Comment by kkoreilly** [comment]
The manual Linux install commands are now listed on the [install page](https://www.cogentcore.org/core/install) as of #1321. Apologies for the delay.
