### ISSUE TITLE
Button Text Sizing is Awkward

### ISSUE THREAD

**Issue by DapperMongoose** [cogentcore/core#1313]
### Describe the bug

Most widgets can be styled to a desired text size with the intuitive use of a styler and setting `s.Font.Size.pt(12)` or `s.Font.Size = units.Pt(12)` however buttons must be styled using the method described in https://github.com/cogentcore/core/issues/1150 which is not intuitive or documented from what I can see.  In addition you must apparently manually set the line height of the button.

### How to reproduce

Create a button
Attempt to style text size in the same manner that you would any other widget

### Platform

Linux

**Comment by kkoreilly** [comment]
Thank you for reporting this. We will improve the documentation and consider redesigning the structure. We will also make it so the line height is automatically set based on the font size.

**Comment by kkoreilly** [comment]
I fixed this in #1340, so the font size of the text in a button is now automatically set to the font size of the button itself. The line height now automatically rescales based on the font size and thus does not need to be set. I will document those changes within a few days.
