### ISSUE TITLE
Allow disabling manual window resizing

### ISSUE THREAD

**Issue by duggavo** [cogentcore/core#1329]
### Describe the feature

Since window resizing is broken and makes the application crash (as seen on https://github.com/cogentcore/core/issues/1247) , a quick fix would be disabling window resize.

However, Cogent Core doesn't seem to have any way to prevent the user from resizing the window.

**Comment by kkoreilly** [comment]
Thank you for filing this issue. We will definitely work on fixing #1247 as soon as we have the time; apologies for the delay. I looked and the underlying `glfw` supports disabling resizing, so we can add an option for that within a week. Given that window resizing works on almost all other platforms, you might want to conditionalize the disabled resizing based on platform.

**Comment by kkoreilly** [comment]
You can do this now with `SetResizable` as of #1341:

```go
b.NewWindow().SetResizable(false).RunMain()
```

Instead of

```go
b.RunMainWindow()
```

(You can do the same thing for non-main windows by using `Run` at the end).
