### ISSUE TITLE
Hello World failed to run within the web

### ISSUE THREAD

**Issue by wingofsky** [cogentcore/core#1366]
### Describe the bug

"core run web" stays on this page

<img width="1641" alt="image" src="https://github.com/user-attachments/assets/1e537e13-17cf-42db-9e62-29fccabea338">

### How to reproduce

1. Use the example to generate hello world [https://www.cogentcore.org/core/basics/hello-world](https://www.cogentcore.org/core/basics/hello-world)
2. core run web
3. Visit http://localhost:8080

### Example code

```go
package main

import "cogentcore.org/core/core"

func main() {
	b := core.NewBody()
	core.NewButton(b).SetText("Hello, World!")
	b.RunMainWindow()
}
```

### Relevant output

```shell
Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.
wasm_exec.js:20 panic: syscall/js: call of Value.Call on null [recovered]
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	panic: runtime error: invalid memory address or nil pointer dereference
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 [signal 0xb code=0x0 addr=0x0 pc=0x0]
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 
writeConsole @ wasm_exec.js:20
wasm_exec.js:20 goroutine 1 [running]:
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system.HandleRecoverBase({0xd8700, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/recover.go:58 +0x1a
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system.init.func1({0xd8700, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/recover.go:33 +0x2
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).SetSystemWindow.func1()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/driver/web/app.go:80 +0x5
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 panic({0xd8700, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/runtime/panic.go:785 +0x1a
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 syscall/js.Value.Call({{}, 0x7ff8000000000002, 0x0}, {0x1cc8d0, 0x9}, {0x2493ae8, 0x1, 0x1})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/syscall/js/js.go:438 +0x3f
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 github.com/cogentcore/webgpu/wgpu.Surface.Configure({{{}, 0x7ff8000000000002, 0x0}}, 0x254e020, 0x254e070, 0x25c6000)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20241209022019-c49c394fb750/wgpu/surface_js.go:27 +0x1d
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).Config(...)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/gpu/surface.go:174
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).InitConfig(0x2570308)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/gpu/surface.go:168 +0x22
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).init(0x2570308, 0x25c06c0, 0x254e030, {0xce0, 0x6ea}, 0x1, 0x0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/gpu/surface.go:83 +0x11
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.NewSurface(0x25c06c0, 0x254e030, {0xce0, 0x6ea}, 0x1, 0x0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/gpu/surface.go:60 +0xd
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).InitDrawer(0x1138ec0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/driver/web/drawer.go:54 +0x3c
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).SetSystemWindow(0x1138ec0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/driver/web/app.go:89 +0xd
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.Init()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/driver/web/app.go:46 +0x15
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver.init.0()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.7/system/driver/driver_web.go:14 +0x1
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:75 exit code: 2
（匿名） @ wasm_exec.js:75了解此错误AI
10wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
app-worker.js:5 installing app worker 9c7e7eabe245f5a7b6c0ac803606ec4d9cc08100
4wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:245:14了解此错误AI
app-worker.js:31 app worker 9c7e7eabe245f5a7b6c0ac803606ec4d9cc08100 is activated
14wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)了解此错误AI
18wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
67wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
59wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
localhost/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received了解此错误AI
55wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
50wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)了解此错误AI
32wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)了解此错误AI
249wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
17wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
```

### Platform

macOS

**Comment by kkoreilly** [comment]
Thank you for reporting this. Does the Cogent Core website load and work correctly for you? Does the page always fail, or is it random? Can you go to chrome://gpu, download the report to a file, and then send it here? Thank you!

**Comment by wingofsky** [comment]
> Thank you for reporting this. Does the Cogent Core website load and work correctly for you? Does the page always fail, or is it random? Can you go to chrome://gpu, download the report to a file, and then send it here? Thank you!

Hello.
The Cogent Core website can be accessed normally
The page I report this problem keeps reporting errors

The following is the downloaded file, please check it
[about-gpu-2024-12-11T06-59-32-744Z.txt](https://github.com/user-attachments/files/18090897/about-gpu-2024-12-11T06-59-32-744Z.txt)

**Comment by kkoreilly** [comment]
Thank you for the information. Can you please try temporarily switching to an earlier version of Cogent Core (`go get cogentcore.org/core@v0.3.5`) and run the app again to help determine what the issue is? Also, it would be useful if you could go to https://compcogneuro.org/sims/ch2/neuron/ and take a screenshot of the behavior: does it load correctly, fail to load, or give an error about 3D rendering?

**Comment by wingofsky** [comment]
> > Thank you for reporting this. Does the Cogent Core website load and work correctly for you? Does the page always fail, or is it random? Can you go to chrome://gpu, download the report to a file, and then send it here? Thank you!
> 
> Hello. The Cogent Core website can be accessed normally The page I report this problem keeps reporting errors
> 
> The following is the downloaded file, please check it [about-gpu-2024-12-11T06-59-32-744Z.txt](https://github.com/user-attachments/files/18090897/about-gpu-2024-12-11T06-59-32-744Z.txt)



1. https://compcogneuro.org/sims/ch2/neuron/ No problem with access
2. I'm in the project
- Deletes the latest core version and go get 0.3.5
- Delete the bin directory generated during the previous 'core run web', re-' run web' with 0.3.5

Still inaccessible and in the browser console

`shell
Banner not shown: beforeinstallpromptevent.preventDefault() called. The page must call beforeinstallpromptevent.prompt() to show the banner.
wasm_exec.js:20 panic: syscall/js: call of Value.Call on null [recovered]
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	panic: runtime error: invalid memory address or nil pointer dereference
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 [signal 0xb code=0x0 addr=0x0 pc=0x0]
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 
writeConsole @ wasm_exec.js:20
wasm_exec.js:20 goroutine 1 [running]:
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system.HandleRecoverBase({0xd7620, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/recover.go:58 +0x1a
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system.init.func1({0xd7620, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/recover.go:33 +0x2
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).SetSystemWindow.func1()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/driver/web/app.go:80 +0x5
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 panic({0xd7620, 0x240a108})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/runtime/panic.go:785 +0x1a
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 syscall/js.Value.Call({{}, 0x7ff8000000000002, 0x0}, {0x1ca5f5, 0x9}, {0x2493af0, 0x1, 0x1})
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/syscall/js/js.go:438 +0x3f
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 github.com/cogentcore/webgpu/wgpu.Surface.Configure({{{}, 0x7ff8000000000002, 0x0}}, 0x255e020, 0x255e070, 0x25c6030)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/github.com/cogentcore/webgpu@v0.0.0-20241209022019-c49c394fb750/wgpu/surface_js.go:27 +0x1d
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).Config(...)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/gpu/surface.go:186
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).InitConfig(0x2570308)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/gpu/surface.go:180 +0x22
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.(*Surface).init(0x2570308, 0x25c2240, 0x255e030, {0xce0, 0x6f4}, 0x1, 0x0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/gpu/surface.go:85 +0x11
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/gpu.NewSurface(0x25c2240, 0x255e030, {0xce0, 0x6f4}, 0x1, 0x0)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/gpu/surface.go:62 +0xd
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).InitDrawer(0x111be40)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/driver/web/drawer.go:54 +0x31
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.(*App).SetSystemWindow(0x111be40)
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/driver/web/app.go:89 +0xd
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver/web.Init()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/driver/web/app.go:46 +0x15
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 cogentcore.org/core/system/driver.init.0()
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:20 	/Users/xutianyi/.g/pkg/mod/cogentcore.org/core@v0.3.5/system/driver/driver_web.go:14 +0x1
writeConsole @ wasm_exec.js:20了解此错误AI
wasm_exec.js:75 exit code: 2
（匿名） @ wasm_exec.js:75了解此错误AI
26wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:245:14了解此错误AI
15wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
app-worker.js:5 installing app worker d9229df750f02c1e6ed6913d3dcec3c50e06b5cf
22wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
app-worker.js:31 app worker d9229df750f02c1e6ed6913d3dcec3c50e06b5cf is activated
8wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)了解此错误AI
62wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8
_resume @ wasm_exec.js:517
（匿名） @ wasm_exec.js:530了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)了解此错误AI
53wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at wasm_exec.js:530:8了解此错误AI
wasm_exec.js:517 Uncaught Error: Go program has already exited
    at Object._resume (wasm_exec.js:517:11)
    at VisualViewport.<anonymous> (wasm_exec.js:530:8)
`

**Comment by kkoreilly** [comment]
Hmm, that is very strange. Can you go back to `v0.3.7` and then make sure that you are using the latest version of the `core` build tool and try again? If that doesn't work, can you clone https://github.com/cogentcore/webgpu, go to `examples/triangle`, and do `core run web -no-generate-html` and see if that works? Thank you!

**Comment by wingofsky** [comment]
> Hmm, that is very strange. Can you go back to `v0.3.7` and then make sure that you are using the latest version of the `core` build tool and try again? If that doesn't work, can you clone https://github.com/cogentcore/webgpu, go to `examples/triangle`, and do `core run web -no-generate-html` and see if that works? Thank you!

Hello.
1. Still at 99% after updating to v0.3.7
2. core run web-no-generate-html fails:

```shell
error: flag name "no-generate-html" not recognized
```
<img width="484" alt="image" src="https://github.com/user-attachments/assets/5f90f2f0-c9ed-4554-8741-20b63b1068a9" />

**Comment by kkoreilly** [comment]
It should be able to find that `no-generate-html` flag, so I think the issue might be the version of the core tool you are using. Can you try running this command to update the core tool and then try again? Thanks!

```sh
go install cogentcore.org/core/cmd/core@main
```

**Comment by wingofsky** [comment]
> It should be able to find that `no-generate-html` flag, so I think the issue might be the version of the core tool you are using. Can you try running this command to update the core tool and then try again? Thanks!
> 
> ```shell
> go install cogentcore.org/core/cmd/core@main
> ```


Hello:
After running install, under the hello world project
1. Direct execution of `core run web` access failed
2. Execute `core run web -no-generate-html` access success
3. Delete the entire bin directory, re-execute `core run web` access successfully, and the page appears new version reload (it looks like this)

It works fine so far. Do I need to try the examples/triangle solution again and provide other information to you?

**Comment by kkoreilly** [comment]
As long as `core run web` is now consistently working with the latest version of the core tool, we do not need to debug further and you can close this issue. Thank you for your help figuring this out!

**Comment by wingofsky** [comment]
> As long as `core run web` is now consistently working with the latest version of the core tool, we do not need to debug further and you can close this issue. Thank you for your help figuring this out!

Thank you very much for your help
