### ISSUE TITLE
form shouldDisplay logic causes crash due to stale captured variables -- updated demo to reveal

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#1390]
### Describe the bug

form contains code like this inside field closures:

```Go
					w.Styler(func(s *styles.Style) {
						f := fm.structFields[i]
```

but the value of `i` depends on what was actually  shown previously, so it can crash with out-of-range errors here. this happens in axon, and I updated the order of fields in demo to show it.

we need a canonical path name, not an index, and to find the field data by that path name.

### How to reproduce

open demo, click things in the first inline guy.

### Platform

macOS

**Comment by rcoreilly** [comment]
@kkoreilly the solution to this bug requires keylist (better ordmap), but that is buried in `goal` repo -- we should just merge that!

**Comment by kkoreilly** [comment]
Shouldn't this logic prevent this issue? https://github.com/cogentcore/core/blob/e7d7703/core/form.go#L165

**Comment by rcoreilly** [comment]
hmm good point, but I think it is the _label_ that is causing the problem it seems. the label widget gets stale and it uses the index for styler and doubleclick closures. We actually do have an existing issue for that: #1098  -- not so rare I guess. The original issue was #1096, which is what the code you're pointing to fixed.

in any case, it is much better to just use the _path_ instead of the index, to get the field data, which obviates both issues. you definitely can't just use f directly -- need to re-get it. but there is actually no need to embed the changable index -- just use the path and lookup in an ordered map of fields by path. will be more efficient too.
