### ISSUE TITLE
close all menus when submenu closes

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#155]
currently leaves parent open, but that's not normal ui behavior.

**Comment by rcoreilly** [comment]
wait, it seems like it DOES close all the menus.  maybe diff is keyboard activation vs. mouse?

**Comment by rohrlich** [comment]
Yes works as expected when selecting with mouse but not with keyboard. Fully reproducible.

**Comment by rcoreilly** [comment]
We need to discuss this: I really like the persistent menus for C-c command menu on gide.. :)  maybe a special option somewhere?  easy to do either way with new stage manager system.

**Comment by kkoreilly** [comment]
It does not make sense to leave the other menus open, as that is completely nonstandard behavior that forces users to put in unnecessary effort to close a menu.
