### ISSUE TITLE
Add to Awesome Go

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#215]
I tried adding GoKi, GoGi, rasterx and Gide to the awesome-go page -- they want a bunch of cleanup docs and more testing:
https://github.com/avelino/awesome-go/pull/2222

These should be improved, they have a lot of issues, especially with golint:
https://goreportcard.com/report/github.com/goki/gi
https://goreportcard.com/report/github.com/goki/ki
https://goreportcard.com/report/github.com/srwiley/rasterx
https://goreportcard.com/report/github.com/goki/gide

These miss a lot of documentation, which should also be improved:
https://godoc.org/github.com/goki/gi/gi
https://godoc.org/github.com/goki/ki
https://godoc.org/github.com/srwiley/rasterx

For whatever reason, this gives no godoc at all:
https://godoc.org/github.com/goki/gide

these don't have enough coverage:
https://github.com/goki/ki
https://github.com/srwiley/rasterx

and these don't even work for any coverage tool
https://github.com/goki/gi
https://github.com/goki/gide

I suggest to close this pull request and sort out all of the repositories in 4 different PRs, so we can help you get things sorted out more easily

**Comment by kkoreilly** [comment]
We should be able to move forward with this after the v1 release, at which point we should have addressed all of those issues.

**Comment by kkoreilly** [comment]
We will do this immediately after the v1 release, so this does not belong in the v1 milestone.

**Comment by kkoreilly** [comment]
We will also add Cogent Core to https://github.com/go-graphics/go-gui-projects after v1.

**Comment by kkoreilly** [comment]
I filed PRs to add Cogent Core to both awesome-go and go-gui-projects.
