### ISSUE TITLE
Implement a canvas widget

### ISSUE THREAD

**Issue by nodrygo** [cogentcore/core#268]
Hello
_first of all this is not a flamewar but just a question_
may be I mistake but I have not see something like _CANVAS_ (not speaking of _SVG_ here)

so the question is do you plan to incorporate in future something like https://github.com/tfriedel6/canvas

not very important because I am only an occasional dev just for fun ;-)

cordially

**Comment by rcoreilly** [comment]
Take a look at gi.Paint -- it is a full "imperative" drawing api, and is how the widgets draw themselves (and is what the SVG uses for rendering).  it is based on https://github.com/fogleman/gg originally but heavily modified.

So you could easily create a new type of gi.Frame for example and do a bunch of those Paint calls to render into it whatever you want.

Assuming you did see that there is full (ish :) SVG rendering too..

**Comment by nodrygo** [comment]
ok will look
thanks

**Comment by kkoreilly** [comment]
We should provide a type that allows you to very easily just set a function field to your rendering function instead of having to declare your own type for this.

**Comment by kkoreilly** [comment]
I implemented an easy to use, standalone canvas widget, `gi.Canvas`, in the commits above.
