### ISSUE TITLE
Register Fullscreen status in oswin Windows, send events?

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#27]
Not clear what the implications are exactly, so not implemented yet, but very straightforward based on what is already there for "minimized" etc.

**Comment by kkoreilly** [comment]
We should also support setting a window as fullscreen from the start.

**Comment by kkoreilly** [comment]
We will not support setting a window as fullscreen from the start, as it does not make any sense to force the user to have fullscreen windows if they do not want them. With the fullscreen remembering that I am implementing now, the user can make a window fullscreen and then it will always be fullscreen on future app startups. The user should be in control of this, and almost no other apps force windows to be fullscreen.
