### ISSUE TITLE
Support validation/constraints on text fields

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#31]
Incorporate https://github.com/asaskevich/govalidator  for `TextField`, and in `ValueView` -- support for things like phone numbers, etc -- can add those constraints "live" while typing etc.

**Comment by rcoreilly** [comment]
do within base TextField widget, adding parts, updating rendering accordingly.

**Comment by kkoreilly** [comment]
As part of this, we need to figure out whether we should support labels directly associated with and placed on text fields.

**Comment by kkoreilly** [comment]
We also need to figure out a good approach to formatting and parsing text field and spinner input as part of this.

**Comment by kkoreilly** [comment]
Validation has been implemented in the commits above.
