### ISSUE TITLE
Create a command line utility that enhances the creation, packaging, and updating of apps

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#499]
Currently, there is a lot of boilerplate code involved in each new project (mainrun, window, viewport, main menu, window event loop, etc). This could be simplified with a `goki new` command. Also, it is currently difficult to package apps with icons and information for different platforms (.msi on Windows, .app on MacOS, .deb on Linux, etc). This could be simplified with a `goki package` command. Furthermore, there is currently no easy way to manage the versions of apps outside of the Go ecosystem.

**Comment by kkoreilly** [comment]
This has been largely implemented (see https://github.com/goki/goki), but more work needs to be done, so I will keep this issue around as a reminder for the v2 milestone.

**Comment by kkoreilly** [comment]
Also, in `goki init`, we need to automatically get the org from the mod url / filepath, automatically get the version package, and initialize the icons if it is an app. We also need to decide on whether to have a separate `goki new`.

**Comment by kkoreilly** [comment]
The config structure of the goki tool also needs to be improved, as we should probably get rid of the output and package fields and stop supporting multiple targets, as all of those things are not really supported and cause problems.

**Comment by kkoreilly** [comment]
Also, we need to support bundling Vulkan with mac apps.

**Comment by kkoreilly** [comment]
We still need to support windows installers, RPM linux packages, and automatic icon backgrounds.

**Comment by kkoreilly** [comment]
And we need to figure out our approach to app icons for Windows.

**Comment by ddkwork** [comment]
> And we need to figure out our approach to app icons for Windows.

https://github.com/gioui/gio-cmd/blob/main/gogio%2Fwindowsbuild.go

**Comment by kkoreilly** [comment]
I implemented automatic embedding of the app icon into apps in 38aa8396ad05f42ffdad4f36822320252c0012cf and the commits after it, meaning that icons are now automatically set on Windows.

**Comment by kkoreilly** [comment]
The `core` tool is now fully functional, and any future improvements to it can be filed as separate issues.
