### ISSUE TITLE
Consider using defer and recover to display a user-friendly error page if an app panics

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#508]
This would be much nicer than the app just quitting, and it would enable people to see and report the error that caused the crash.

**Comment by kkoreilly** [comment]
The infrastructure is in place for this to be implemented (`goosi.HandleRecover`), but we still need to figure out how to do this and still have the app still panic when debugging.

**Comment by rcoreilly** [comment]
we lost even the basic crash log with the removal of gimain -- would be great to get that back asap :)

**Comment by kkoreilly** [comment]
Implemented in 9f035aa.
