### ISSUE TITLE
New windows are sometimes placed offscreen on Windows due to a failure to account for the size of the title bar

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#509]
There are checks in there that are supposed to prevent this, but they aren't working!

**Comment by kkoreilly** [comment]
I have been experiencing this on Windows some (also with windows starting offscreen); I think it is getting confused with the size of the title bar.

**Comment by rcoreilly** [comment]
@kkoreilly is this still a thing?  I haven't seen it in a while.

**Comment by kkoreilly** [comment]
I will rename this issue to be more accurate regarding the actual problem.

**Comment by kkoreilly** [comment]
This is all fixed now as of #1341.
