### ISSUE TITLE
Add significantly more unit tests for v1

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#541]
It is impossible for GoGi to be fully reliable without a lot more unit tests, including ones on actual UI elements, not underlying calculations.

**Comment by kkoreilly** [comment]
This must be implemented for v2.

**Comment by ddkwork** [comment]
There are currently several packages that cannot be skipped for testing, and GitHub action failures seem to be the same. When the code testing coverage is high, I imagine that beginners like me will be more likely to learn drawing logic

**Comment by kkoreilly** [comment]
I will definitely work on implementing a lot of tests after I finish some of the other issues.

**Comment by kkoreilly** [comment]
I added many more unit tests, and all of the infrastructure is in place and working for image-based GUI testing. We are now above 40% test coverage, which is similar to other Go GUI frameworks and perfectly sufficient for v1. I will file a separate long-term issue about adding more unit tests, as that is an ongoing process and we do want to increase test coverage more eventually, but that will not be a high priority for now.
