### ISSUE TITLE
Support box shadow blur

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#570]
The box shadow blur property exists but is not supported. Supporting blur is critical for box shadows to actually be helpful and not look terrible.

**Comment by rcoreilly** [comment]
https://stackoverflow.com/questions/7364026/algorithm-for-fast-drop-shadow-in-gdi

Key points: 
* cache rendered shadow for given params -- ideally something that tiles cleanly without looking tiled
* use 2x 1d kernels instead of a 2d kernel to render initially.

**Comment by kkoreilly** [comment]
This has been implemented, but we still need to fix minor asymmetry and an out of range issue.

**Comment by kkoreilly** [comment]
The out of range issue seems to happen when an element with a box shadow is cut off by the window (maybe related to #723).

**Comment by rcoreilly** [comment]
out of range fixed

**Comment by kkoreilly** [comment]
The asymmetry was fixed by #810, so box shadow blur is now fully working.
