### ISSUE TITLE
Display type of element in the inspect editor

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#580]
Most of the time, it is easy to figure out what type of element you are viewing, but sometimes it can be difficult while viewing elements that you didn't write the code for. It would be helpful to add an easy way to view this information.

**Comment by rcoreilly** [comment]
pro tip: if you look at the tooltip on UpdtView, it is shown there :)

**Comment by rcoreilly** [comment]
(for a structview)

**Comment by kkoreilly** [comment]
We need to do this, and may want to do this more generally for struct, map, and slice views, etc.

**Comment by kkoreilly** [comment]
This is also related to our dialog title and text structure more broadly.
