### ISSUE TITLE
Triggering a full update on a window with F5 can cause it to relocate

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#603]
In particular, when using multiple monitors, this change can be quite extreme and put it outside of the bounds of the monitor.

**Comment by kkoreilly** [comment]
This is still a major issue.

**Comment by kkoreilly** [comment]
There are also more issues with multiple monitors that we need to fix, such as #632, #509, and whether windows opened in the context of a window on one monitor should always open on that monitor instead of going to the main monitor.

**Comment by kkoreilly** [comment]
This still happens, but only with multiple monitors.

**Comment by kkoreilly** [comment]
We also need to resolve our approach to screen-specific settings, like for zoom.

**Comment by kkoreilly** [comment]
Also, windows are now sometimes getting smaller on F5.

**Comment by theclapp** [comment]
I see this on a Macbook Pro 2019 15" with an external monitor. I have the external monitor set as the "main" monitor. I put the demo on the builtin laptop screen and pressed F5, it jumped to the external monitor.

When it jumped it retained (approximately?) the same size and zoom, but when I pressed Cmd-+ (plus) and Cmd-- (minus) it reset to the "actual" zoom: On the builtin display, 100% is fine; on the external display, I have to use about 400%.

The builtin monitor is 2880x1800 (native), which I run at 1680x1050 (the default); the external is a ViewSonic vx3211-4k, 3840x2160 (native), which I run at 3200x1800.

**Comment by kkoreilly** [comment]
Yes, the key issue here is that we are currently not saving the monitor a window is on, so anytime you F5, it resets to the main monitor. There are some issues in glfw in terms of how you determine what monitor something goes on, but it shouldn't be too hard to implement.

**Comment by kkoreilly** [comment]
This is all fixed now as of #1341.
