### ISSUE TITLE
Implement more color selection methods in color picker and support more types of gradients

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#619]

**Comment by kkoreilly** [comment]
We still need to implement named color selection (and more options for color selection in general) in the ColorView.

**Comment by kkoreilly** [comment]
Also, we need to fix HCT slider syncing and use a conic gradient for hue.

**Comment by kkoreilly** [comment]
A history of recently selected colors would also be helpful.

**Comment by kkoreilly** [comment]
We need to first fix our HCT gradient handling and implement conic gradients.

**Comment by rcoreilly** [comment]
Added efficient rendering for non-RGB gradients in 426b4b3766c754579febf93b0d8c455f4fb63699

**Comment by kkoreilly** [comment]
(and a4ac4976ee0c592700aa59bf8549a1c6f8f93068).

**Comment by kkoreilly** [comment]
I improved the color picker a lot in accordance with all of these things, so this issue can be closed now. The only remaining gradient feature missing is conic gradients, which are now moved to #1000.
