### ISSUE TITLE
Add support for cursor shadows

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#662]
At least need shadows, so it stands out in all cases.

The disabled cursor also is effectively invisible -- specifically bad case of this.

**Comment by kkoreilly** [comment]
We also may want to consider whether we should render the cursor from SVG ourselves, which would give us a lot more control over its colors and other attributes.

**Comment by kkoreilly** [comment]
We are rendering cursors from SVG as of the commits above, and #1372 implements cursor shadows among other fixes. Further cursor features are tracked by #1373.
