### ISSUE TITLE
Run race detector in V2

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#671]
should be all good but might be a few cases here and there.

Also, can look at need for style and other mutexes -- in general most likely not needed due to way things get updated and top-level UpdateStartAsync logic.

**Comment by kkoreilly** [comment]
The Goki Demo fails to start very occasionally on my windows computer; I would say about 1% of the time.

**Comment by rcoreilly** [comment]
Did this with async test example, and it looks pretty clean (after fixing some things): just the atomic flag checking routines -- which are fine.

key command for running that prevents immediate fail in vulkan / glfw:

```
go build -race -gcflags=all=-d=checkptr=0
```

**Comment by rcoreilly** [comment]
just commented out StyMu and BBoxMu and ran async race detector without any additional issues related to those things, so likely can remove pending further testing.

fbf166eec

**Comment by rcoreilly** [comment]
to be more explicit: *everything* is protected by the RenderCtx mutex lock that happens at the start of event processing, rendering, and Async processing, so we don't need finer-grained mutexes within widgets etc.  This strategy precludes parallel processing of widgets, but that doesn't make sense for lots of reasons anyway, so this big global mutex strategy is probably the best way to go.

**Comment by kkoreilly** [comment]
After more testing, it is clear that `StyMu` and `BBoxMu` are not necessary, so I cleaned up the old code for that in the commit above. The race detector output seems to be good, and there are no clear outstanding issues, so I will close this issue.
