### ISSUE TITLE
Fix row selection in tables

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#672]
When a table row is selected, the whole row should be consistently highlighted, not just the individual elements in it. This is related to #620.

**Comment by ddkwork** [comment]
> When a table row is selected, the whole row should be consistently highlighted, not just the individual elements in it. This is related to #620.

Yes, it is true that the background color of the selected row needs to be rendered, and after observing the table rendering of the giv tableview, it is found that when the control type of each cell of the row is different, the height of the control is inconsistent, resulting in the appearance of the whole row looking uneven. In addition, is there an API to respond to this kind of event: when you click or select a row, take all the cell contents in the row, for the data-bound struct, in fact, the cells of the whole row just represent the instantiated values of all the fields of a struct, I am ready to replace the GUI library of a packet grabber as gogi, and I find that the onSelected method of the table cannot be found, and I don't know how to get the row data. In addition, for the debugger interface, some additional features are needed to display more data, such as: setting to hide the header, setting to hide the row separator, setting the zebra crossing with different background colors for the odd and even rows, etc.

**Comment by kkoreilly** [comment]
Yes, I am planning to implement all of those things soon.

**Comment by kkoreilly** [comment]
We also need to fix double click events being sent incorrectly when clicking in rapid succession on the side of a slice / table view.

**Comment by kkoreilly** [comment]
We also need to fix right click and focus handling in table views.

**Comment by rcoreilly** [comment]
b8030b8413e2d8c098d72dcc10599bf6edcb94d9

**Comment by kkoreilly** [comment]
Table and slice view row selection, styling, drag and drop, and all other things have been fixed in the commits above.
