### ISSUE TITLE
Implement a vulkan-free driver for VMs and old devices

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#682]
It would be useful to be able to run in virtual machines and remote desktops.

Vulkan in software may be getting better in various forms (mesa, some other thing that android or ios uses in its simulator).

Alternatively, the 2D framework is now working well using non-vulkan impl of drawer interface -- could reasonably support 2D only using a much simpler API that only uses this bitmap-based interface, running on some kind of really basic glfw window interface (not even opengl).  That would be worth it for allowing majority of apps to run in VMs etc.

See #483 for example where it doesn't work.

**Comment by kkoreilly** [comment]
It has worked fine on VNC in my experience.

**Comment by ddkwork** [comment]
Also, it would be nice if I could support termux, I used termux for a long time before buying a tablet, it was as smooth as Windows xp, using the xfce interface

**Comment by kkoreilly** [comment]
This also affects chromebooks, which do not support Vulkan by default. I am running into this while working on #321.

**Comment by kkoreilly** [comment]
At some point, we will implement WebGPU support (#507), which may remove the need for adding a backup 2D vulkan-free driver. Even if we do still need to implement a separate compatibility driver, doing so will not be especially quick, and we have limited time before our initial release. Therefore, we will work on resolving this later, as everything works properly on the vast majority of devices already.
