### ISSUE TITLE
Support text field wrapping and better overflow options

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#697]
There should be an option to have text fields wrap to multiple lines. Also, we should support text fields expanding horizontally some to fit their contents.

**Comment by kkoreilly** [comment]
Also, text fields sometimes become impossible to use when there is too much in them or the spacing is too high, as they start to glitch and become hard to navigate or see.

**Comment by kkoreilly** [comment]
We also need to figure out how to structure the text field max width.

**Comment by rcoreilly** [comment]
Multi-line textfield is now supported -- if you style it with SetTextWrap(true) or just set WhiteSpaceNormal + GrowWrap

Also even single-line textfields now do a re-layout on EditDone so they will update size if it got bigger -- but still scroll while initially entering -- but we could do size-updating while typing, but I think that is not great.
