### ISSUE TITLE
Not all elements are updating on settings changes

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#709]
We may need to handle some global `Restyle`/`Rebuild` flag.

**Comment by ddkwork** [comment]
I agree with this opinion, on Win11 and Android devices, you have to set zoom to 50%-80% every time for it to display properly

**Comment by kkoreilly** [comment]
Text editor and xyz are the main things that need to be fixed for this; xyz will require a major redesign of the 3d styling paradigm.

**Comment by rcoreilly** [comment]
xyz is fixed in 6b257619fe57dc62d90173941b40f1994ee96ffd , using styler on the outer core widget for the background color and logic in Text2D that detects usage of standard font color and updates it accordingly.

**Comment by rcoreilly** [comment]
texteditor histyle here: 5c74c765a

**Comment by kkoreilly** [comment]
There are still some issues with scrollbars and text field cursors not updating on theme change. Also, we still need to redesign xyz to use updaters and plans (#1022), which will fully resolve theme changing for xyz.

**Comment by kkoreilly** [comment]
Note that the scrollbars also do not update in the interactive styling demo in the docs and demo due to their insulation from the normal updating process, so we may want to just implement `NodeWalkDown` on `Frame` for them so that they always update properly.

**Comment by kkoreilly** [comment]
We fixed the scrollbars and cursors in #1339, so the only remaining issue is xyz, which is a separate issue (#1022).
