### ISSUE TITLE
Improve the structure of giv

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#752]

**Comment by kkoreilly** [comment]
We should consider this as part of a broader giv redesign to reduce significant amounts of inelegant and duplicated code.

**Comment by kkoreilly** [comment]
For example, we should reduce the boilerplate needed for value dialogs and config.

**Comment by kkoreilly** [comment]
We should also clean up unnecessary setters on giv views.

**Comment by rcoreilly** [comment]
Do whatever you can without eliminating functionality please.  I don't see any need for further discussion -- if you have a specific proposal that seems like it would be a bad idea, we can discuss that!

**Comment by kkoreilly** [comment]
I did this in #937.
