### ISSUE TITLE
Resolve dialog structure

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#753]
We need to figure out if we can simplify the bottom bar and whether it should be `AddOK` or `AddOk`.

**Comment by rcoreilly** [comment]
Do not rename AddOK unless your OCD _absolutely_ requires it.  There is plenty of "legal" room to use Ok as a short version of okay: https://www.merriam-webster.com/dictionary/OK

OK looks like SCREAMING and we just don't need more of that!

Bottom bar is fine and provides a simple unified structure across all use cases.  leave it be.

**Comment by kkoreilly** [comment]
We have decided that the current bottom bar structure is good and `AddOk` is ok.
