### ISSUE TITLE
Resolve display of keyboard shortcuts

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#756]
We need to hide keyboard shortcuts on mobile and determine whether we should use unicode characters for them on any or all platforms.

**Comment by kkoreilly** [comment]
Also, we need to consider chord chaining methods.

**Comment by rcoreilly** [comment]
Currently doing mac special chars on mac, which is standard, and it should just be left as it is.

**Comment by kkoreilly** [comment]
We still need to hide keyboard shortcuts on mobile.
