### ISSUE TITLE
Decide on our approach to em dashes

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#757]
The codebase is polluted with improperly formatted em dashes (`--`), which look bad and lead to run-on sentences that are not good for end user comprehension. Material even says:

> Em dashes are best avoided in UX writing, as they indicate a break in the flow of a sentence that could be simplified using a comma, period, or new sentence. 

(Source: https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation). Therefore, we should consider a systematic removal of em dashes from the code base, or at least a rendering method that renders them as real em dashes instead of double hyphens.

**Comment by rcoreilly** [comment]
wherever possible render as proper em dashes, and in general try to get rid of them.  this is not easily automated, but if it could be, that would be great!

**Comment by kkoreilly** [comment]
We can not get rid of em dashes with a simple find and replace, as that is not guaranteed to be syntactically valid, and semicolons are not much better than em dashes. We just need to have well-written, complete sentences with periods, and we will continue to work on that over time whenever we work on different parts of the codebase. However, there will be no systematic rewrite and no global issue, as that is not a critical, high priority task worth spending a lot of time on. Also, we can not just render double dashes as em dashes, as that would be imposing our will on everyone, which would prevent people from ever having double dashes for any reason in any Cogent Core app. Therefore, this issue is resolved.
