### ISSUE TITLE
Previous window not getting focus after a separate window dialog is closed (desktop, mac)

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#804]
e.g., fileview choosers -- doesn't return focus back to gide for example.

this logic used to be in there -- unfortunately OS doesn't do this automatically (on mac at least -- can't remember about other desktop platforms)

**Comment by rcoreilly** [comment]
this is (not) happening again (previous window is not getting focus).

**Comment by kkoreilly** [comment]
I fixed this in the commits above and also greatly improved the structure of focus window history tracking.
