### ISSUE TITLE
windows are still not fully closing

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#805]
if you close all the windows in an app, the app itself should quit, due to the wait condition.  this often, but not always, happens.

**Comment by rcoreilly** [comment]
Looks like it might be stuck in a mutex hang around the rendercursor in texteditor.

**Comment by rcoreilly** [comment]
we were not even deleting the window contents -- now doing that, and destroy closes the cursor -- looks like it is fixed.  will reopen if recurs.

**Comment by rcoreilly** [comment]
this is now happening semi-reliably (but not exactly reproducible). things look like they are in some kind of zombie-like state when I debug attach.  maybe some recent goosi / event loop change for testing stuff?  @kkoreilly ?

**Comment by kkoreilly** [comment]
I don't think I have done anything recently that could have caused this.

**Comment by rcoreilly** [comment]
I added more direct route to turning off cursor which seemed to be the problem - now working

**Comment by rcoreilly** [comment]
yep, happening again: just caught one in the act -- waiting on the texteditor.ViewBlinker channel (just renamed to EditorBlink*) in texteditor/cursor.go -- need a quit cleanup call..

**Comment by rcoreilly** [comment]
also for same thing in textfield

**Comment by kkoreilly** [comment]
Fixed in c129af4.

**Comment by rcoreilly** [comment]
its baaak...  definitely happening.

**Comment by rcoreilly** [comment]
My simulations in axon are now 100% reliably not closing.

**Comment by rcoreilly** [comment]
furthermore, I can verify that a build from 2/14 did close (immediately after starting), while the same thing built now fails to quit.  thus, it was a relatively recent change

**Comment by rcoreilly** [comment]
@kkoreilly  this is happening in demo too.  please fix.
