### ISSUE TITLE
Overflow auto (scrollbars) not supported on elements with a defined max

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#808]

**Comment by kkoreilly** [comment]
Various scrolling tests should be updated/added when doing this to confirm that it works; search for `TODO(#808)` to start.

**Comment by rcoreilly** [comment]
Would be good to have more info here -- I've since forgotten what this is all about.  need a test case.

**Comment by kkoreilly** [comment]
This seems to be largely working, but there are still some remaining issues with this and #615, as shown by the test for #615.
