### ISSUE TITLE
Support moveable and resizable non-full non-new stages/dialogs and scrims

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#812]

**Comment by rcoreilly** [comment]
Scrims will be done in direct rendering (do we have a ticket for that?)

Added handle for positioning dialogs.  it works. I tried for too long to get it to render in the margin at top of window, but failed -- see code in scene.go, ScenePos() and Render() functions.

**Comment by rcoreilly** [comment]
scrims in #912

**Comment by rcoreilly** [comment]
done in 346668c3d
