### ISSUE TITLE
spinner rounding is failing badly

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#819]
I tried to enter 99534 into spinner to attach to a process, and it converted it to 99533.99 which rounded down to ..32  

and I'm seeing line 1192.9 in my debug list

**Comment by rcoreilly** [comment]
This is the culprit.  reverting to horrible-but-functional sprintf-based version that works reliably.   there was a reason I didn't go this route before.

	sp.Value = mat32.Truncate(sp.Value, sp.Prec)

**Comment by kkoreilly** [comment]
I added a todo about making `mat32.Truncate` faster, but it probably isn't that much of a problem and thus it doesn't seem worth doing now.
