### ISSUE TITLE
Consider supporting an easier way for end-users to handle widget part names

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#840]
### Describe the feature

For example, if someone wanted to do something specific with the label of a button or the trailing icon of a textfield, currently they would have to guess the names of those parts.

**Comment by rcoreilly** [comment]
Add constant strings. Eg ButtonLabelName - just the name - add a function to make parts path.

**Comment by kkoreilly** [comment]
We are not going to implement this, since it would be a significant addition of code and API bloat for an unclear end. Very few people should need to customize the parts of a widget in `OnWidgetAdded`, and if they do, they can find the name in the code or in the inspector. Furthermore, the names are not really rocket science: the label of a button is "label", the icon is "icon", the indicator is "indicator", etc. Also, there are already helper functions in some places where it would be necessary to get the widget (`Button.SetTextUpdate`, `TextField.LeadingIconButton`, etc).
