### ISSUE TITLE
svg gradient rendering is not working for some cases (fig_cortex_lobes.svg) and colors/gradient tests are failing

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#843]
### Describe the bug

in `svg/testdata/svg/`

* fig_cortex_lobes.svg -- fixed the viewbox so the render is fully visible now, but the radial gradient is definitely not working -- completely flat

* fig_neuron_as_detect.svg, fig_bp_compute_delta.svg -- arrow heads are missing.

### How to reproduce

run the test, look at the .png :)

### Platform

macOS

**Comment by rcoreilly** [comment]
markers are fixed, but gradients are failing at the source: colors/gradient/gradient_test is failing.

also added a very simple radial gradient test to svg test images, which fails.

need to fix this one together.

**Comment by kkoreilly** [comment]
Guess what you got mad at me for trying to fix yesterday: the failing gradient tests.

**Comment by rcoreilly** [comment]
gradient transforms are now finally all good: had issues in mat32.Mat2 mul *and* Inverse.  todo: write tests for mat32 Mat2 and Mat3 (suspect it might not be right either).

meanwhile, there is a problem with premultiplied opacity / alpha, as in srn_time_predict or vm_tug_of_war, with opacity in the gradient stops.  Kai will fix this one remaining problem, add the explicit gradient tests, and add the code that generates RGB stops from HCT color stops (RGB should always be used behind the scenes).

**Comment by rcoreilly** [comment]
all good now -- just needed separate opacity values per stop, as in the original rasterx impl, and svg spec.

**Comment by rcoreilly** [comment]
95d43a9fe7c26de6cd3b7a69dfd661445ecad107
