### ISSUE TITLE
Goki.dev/enums now missing breaks for existing developers

### ISSUE THREAD

**Issue by ChronosMasterOfAllTime** [cogentcore/core#844]
### Describe the bug

I understand that we moved from goki.dev to cogentcore.org. That being said, it's not called out on the https://goki.dev main site, and the enums package was wiped from github. There should at least be an alias and an archive of the exist repo, pointing users to cogentcore. I wouldn't have known had my github actions runners not failed.

### How to reproduce

Use a project with goki.dev/enums 0.9.52

### Relevant output

```shell
proxy | 2024/01/22 16:10:15 [017] GET https://goki.dev:443/enums?go-get=1
  proxy | 2024/01/22 16:10:15 [017] 301 https://goki.dev:443/enums?go-get=1
  proxy | 2024/01/22 16:10:15 [019] GET https://goki.dev:443/enums/?go-get=1
  proxy | 2024/01/22 16:10:15 [019] 200 https://goki.dev:443/enums/?go-get=1
  proxy | 2024/01/22 16:10:15 [021] GET https://github.com:443/kataras/iris/info/refs?service=git-upload-pack
  proxy | 2024/01/22 16:10:15 [021] * authenticating git server request (host: github.com)
  proxy | 2024/01/22 16:10:15 [023] GET https://github.com:443/goki/enums/info/refs?service=git-upload-pack
  proxy | 2024/01/22 16:10:15 [023] * authenticating git server request (host: github.com)
  proxy | 2024/01/22 16:10:15 [023] 404 https://github.com:443/goki/enums/info/refs?service=git-upload-pack
```

### Platform

macOS

**Comment by kkoreilly** [comment]
Apologies for the sudden and unannounced move. I will add a notice to the goki.dev website and will consider adding an archived version of the enums repository.

**Comment by kkoreilly** [comment]
I added a notice about the rename to the website. Because enums was a v0 unstable package, we will not provide a archive of it at the old URL. People who were using it can move to the new url, `cogentcore.org/core/enums`. Apologies for the inconvenience.

**Comment by ChronosMasterOfAllTime** [comment]
Thank you!
