### ISSUE TITLE
Need a way to turn off sentence casing labelizer on StructView[inline]

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#859]
### Describe the feature

For scientific models (my neural net sims), I have parameters that are amalgams of abbreviations with standardized (and irregular) scientific capitalization structure (e.g., ACh, NAc, GgabaB), which become complete soup in the sentence caser.

The simplest way to do this would be a global option, in giv: `SentenceCaseLabels` -- otherwise you'd have to specify something per struct which would be unwieldy. 

Alternatively, gti could potentially have an option somewhere, so the generate command does it for everything in a given package, which would be ideal.

**Comment by kkoreilly** [comment]
We already have a `label` struct tag that bypasses the sentence caser. We could just add an option to have it be the same as the original field name (eg: `label:"."`)

**Comment by kkoreilly** [comment]
We could also just make the sentence caser handle things like that better (see #772).
