### ISSUE TITLE
How to specify ext extension in FuncButton for method taking gi.Filename arg?

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#860]
### Describe the feature

need to be able to specify the file extension that a given gi.Filename is looking for, as an arg to a method, where FuncButton will pull up the FileView.  The FileValue looks for an "ext" tag with the extension(s).

**Comment by kkoreilly** [comment]
Just do this: `fb.Args[0].SetTag("ext", ".json")` (or any other argument index or extension). You can see this done already throughout the codebase, especially in Cogent Code.

**Comment by rcoreilly** [comment]
thanks -- need docs for this!

**Comment by kkoreilly** [comment]
That will happen in the context of #491.
