### ISSUE TITLE
table on select

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#865]
### Describe the bug

The cell height is inconsistent, so that the focus of the selected row cannot be hit every time, and sometimes the row cannot be selected after several clicks

### How to reproduce

![Screenshot_20240204_165928_com ux taskmanager](https://github.com/cogentcore/core/assets/19886504/e8197574-e4fa-4c02-b88a-36c7e4afacbc)

### Platform

macOS

**Comment by kkoreilly** [comment]
We just implemented basic consistent selection styling and zebra striping in #672, but there are still some issues, including those that you mentioned. We will track those issues in #672, so this is a duplicate.
