### ISSUE TITLE
vmware

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#873]
### Describe the feature

![image](https://github.com/cogentcore/core/assets/19886504/5e1d9e99-4844-4228-a65a-24a37f1ea41a)

### Relevant code

```go
run core on vmware
```

**Comment by ddkwork** [comment]
On the Win11 system of the physical machine, vulkan is installed by default, but on VMware, I installed the latest version of the vulkan sdk and ran config and found that the driver was not loaded, so I should install the same version of the sdk as the physical machine? I'm going to test how GIO works again in both environments.

**Comment by kkoreilly** [comment]
This is a duplicate of #682. We are considering adding an image-based fallback option to render on systems without Vulkan, like virtual machines.
