### ISSUE TITLE
back arrow cannot close main window!

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#884]
### Describe the bug

the existing logic is apparently that if you're the last full window open, back arrow doesn't close you.

but in my simulation, I had some other windows open (shift + edits) and accidentally hit the back arrow too many times in my main sim window, and "poof" it went away, taking some interesting learned weights with it :(

Need better logic here, with some kind of flag or other property designating a main app window that cannot be closed by the back button!

### How to reproduce

do it!

### Platform

macOS

**Comment by rcoreilly** [comment]
proposed solution is that we add a flag for this on Stage (CloseOnBack), set this to true for all Dialog by default, false for all other FullWindow stages.  thus, it can be overridden, but has sensible defaults.  Inspector and Settings should be dialogs, to get these appropriate defaults, and befitting of their actual status.

**Comment by kkoreilly** [comment]
I implemented this in the commits above with a new `CloseOnBack` option on `Stage`.
