### ISSUE TITLE
table select slow

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#892]
### Describe the bug

The line rendering speed of the table can't keep up with the speed of the mouse machine, and there is a delay, which is more serious than this in the real scene, because the demo is delayed for 1 second to simulate user operations, we can change the time size of the delay to test it, and generally the delay feels obvious after adding 10 lines

### How to reproduce

![screenshots](https://github.com/cogentcore/core/assets/19886504/4280f325-1792-4086-b900-47aba334784b)

### Example code

```go
// Command async demonstrates async updating in Cogent Core.
package main

import (
	"time"

	"cogentcore.org/core/events"
	"cogentcore.org/core/gi"
	"cogentcore.org/core/giv"
	"cogentcore.org/core/icons"
)

type tableStruct struct {
	Icon       icons.Icon
	IntField   int
	FloatField float32
	StrField   string
	File       gi.Filename
}

const rows = 100000

func main() {
	table := make([]*tableStruct, 0, rows)
	b := gi.NewBody("Async Updating")
	tv := giv.NewTableView(b)
	tv.SetReadOnly(true)
	tv.SetSlice(&table)

	b.OnShow(func(e events.Event) {
		go func() {
			for i := 0; i < rows; i++ {
				updt := b.UpdateStartAsync()
				table = append(table, &tableStruct{IntField: i, FloatField: float32(i) / 10.0})
				tv.UpdateWidgets()
				if len(table) > 0 {
					tv.ScrollToIdx(len(table) - 1)
				}
				b.UpdateEndAsyncLayout(updt)
				//time.Sleep(1 * time.Millisecond)
				time.Sleep(1 * time.Second)
			}
		}()
	})

	b.RunMainWindow()
}
```

### Relevant output

```shell
see title
```

### Platform

Windows

**Comment by ddkwork** [comment]
I don't feel like it's a mutex repelling it

**Comment by kkoreilly** [comment]
I can reproduce this issue: the cause of the issue is not that the table selection is "slow", but that there is a bug that causes table selection via widgets to not work for scrolled table views. I will work on fixing this bug today.

**Comment by ddkwork** [comment]
> I can reproduce this issue: the cause of the issue is not that the table selection is "slow", but that there is a bug that causes table selection via widgets to not work for scrolled table views. I will work on fixing this bug today.

It's a perfect fix!
