### ISSUE TITLE
texteditor output buff in code is not getting scrollbars on initial render (e.g., for diffs)

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#900]
### Describe the bug

see title

### How to reproduce

diff in cogent code with lots of diffs

### Platform

macOS

**Comment by rcoreilly** [comment]
this is regression from latest update to texteditor layout update.

**Comment by rcoreilly** [comment]
also not scrolling at the end either.

**Comment by rcoreilly** [comment]
the final update call is happening in:

```go
texteditor/buf.go: func (tb *Buf) AutoScrollViews() {
```

I added an ed.SetNeedsLayout there, but it is getting swallowed somehow (and for ed.Layout.SetNeedLayout too)

**Comment by rcoreilly** [comment]
Also getting the situation where initial click on link (e.g., in find, err) does not jump to the correct position until a key event triggers a render update.

**Comment by rcoreilly** [comment]
also jump to line doesn't work the first time.

**Comment by rcoreilly** [comment]
This appears to be specific to Code -- not replicable in any of the cases in plain texteditor example.

**Comment by rcoreilly** [comment]
Jump to line had a bizarre ge.Indent call stuck in it -- removing that seems to fix that issue.

the find link clicks seem to be due to LongPress intruding -- increasing this to 1s fixes this issue.

the original  issue here is still present but fixes itself immediately after any render update is triggered, so it is lower pri.

**Comment by kkoreilly** [comment]
So will you close the issue?

**Comment by rcoreilly** [comment]
Jump is still not working again actually -- on first time in a new file.

and link click is still pulling up a context menu!

**Comment by rcoreilly** [comment]
recent fixes have resolved the important aspects of this.  will file more specific issues if anything else comes up.

**Comment by kkoreilly** [comment]
All text editors no longer have scrollbars on initial render, and they also do not get allocated enough space. This regression happened sometime during the big renaming PR.

**Comment by rcoreilly** [comment]
This is not a regression: the separate texteditor demo still works (and code still works for main editors) with latest.  It is something to do with having the editors within the demo tabs structure.  this is consistent with the fact that the scrollbar issue only happens in code for tabs.  will investigate.

**Comment by kkoreilly** [comment]
Again, this issue also happens in the documentation and unit tests, and it is not limited to tabs.

**Comment by rcoreilly** [comment]
I am seeing scrollbars in docs.  

re the sizing: I don't think there is really a sensible universal default size for a texteditor -- would it make more sense to just  specify that as needed, in the docs?

**Comment by rcoreilly** [comment]
This is now fully fixed I hope! initial layout was being done before enough size info was avail -- now doing in SizeDown and seems to be working reliably.  also fixed the issues with autoscroll in code.
