### ISSUE TITLE
resizing windows on mac used to re-render continuously, now does not

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#901]
### Describe the bug

see title

### How to reproduce

resize a window

### Platform

macOS

**Comment by kkoreilly** [comment]
This happened at some point between v0.0.3 and v0.0.4

**Comment by kkoreilly** [comment]
This regression was introduced in 8c932de.

**Comment by kkoreilly** [comment]
The cause of this issue is that `OnShow` is being called every time the window is resized, so we are spamming the title update and preventing normal resizing.
