### ISSUE TITLE
completer popup is not going away sometimes

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#904]
### Describe the bug

in Code, typing, doesn't go away

### How to reproduce

seems fairly random unfortunately.  can still hit esc or click off to get it to close, so its not perma-stuck.  some kind of mutex issue undoubtedly.

### Platform

macOS

**Comment by kkoreilly** [comment]
This no longer seems to happen; this issue can be reopened if it does.

**Comment by rcoreilly** [comment]
yep still happening.  need to figure out conditions for reproducing.

**Comment by rcoreilly** [comment]
this should now be fixed -- don't use async for 0 delay case.
