### ISSUE TITLE
Redesign the log

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#906]
### Describe the feature

This is a low priority, and I found that when there is too much source code, the log needs to have the following functions to make it easy to quickly locate the source code with a mouse click

**Comment by ddkwork** [comment]
![{13B3262D-18E9-4a0f-BC0E-F97C774C563B}.png](https://github.com/cogentcore/core/assets/19886504/bb0610ee-e3b2-46cd-a261-d9d273a8837c)

**Comment by kkoreilly** [comment]
It is your responsibility to write log messages that are clear and sufficiently convey the location; I am always able to find log messages just by searching for the message. We are not going to force people to have information they do not want in their log messages; you can easily write a helper function that does this if you want that behavior.

**Comment by ddkwork** [comment]
> It is your responsibility to write log messages that are clear and sufficiently convey the location; I am always able to find log messages just by searching for the message. We are not going to force people to have information they do not want in their log messages; you can easily write a helper function that does this if you want that behavior.

ok
