### ISSUE TITLE
add direct rendering for XYZ and scrims

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#912]
### Describe the feature

was in V1, just port over to new infra

**Comment by rcoreilly** [comment]
xyz is done in 1ad92ccd8f6dcef433eba562ea70e7084f003814 -- also need to support video

**Comment by rcoreilly** [comment]
scrim in 589f9afdc3aff4b80e2b14c71ef67586b6b53c41 -- still need video

**Comment by kkoreilly** [comment]
Direct rendering was added and implemented for xyz and scrims in the commits above, so this issue is complete. Video is #516.
