### ISSUE TITLE
duration value has many issues

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#913]
### Describe the bug

* does not change units properly -- should auto-convert current value to value in new units
* in Settings, LongPressTime now is 1s, but you can't + without it going to 0 and this then breaks clicking entirely. also doesn't allow typing a value into the field.
* needs to support things like 1.1 sec etc.  
* should parse standard step, min, max tags

### How to reproduce

tried to reproduce in demo with tags but not reading tags etc.

### Platform

macOS

**Comment by kkoreilly** [comment]
The standard tags issue is #816.

**Comment by kkoreilly** [comment]
I fixed all of these issues in the commits above, except for the tags one, which is #816 as stated above.
