### ISSUE TITLE
setting a non-standard keymap in settings causes it to incorrectly write all keymap info to device-settings.toml 

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#914]
### Describe the bug

see tittle

### How to reproduce

see title.

### Platform

macOS

**Comment by kkoreilly** [comment]
This is expected behavior; non-default saving is based on struct fields, and there is only one struct field for the whole key map, as it is just a map.

**Comment by rcoreilly** [comment]
It should just save the one `KeyMap` field, not the `KeyMaps`:

```
KeyMap = 'MacEmacs'

[KeyMaps]
[[KeyMaps.Value]]
...
```

KeyMaps is Set = false

![image](https://github.com/cogentcore/core/assets/9605819/5fd9d78b-8541-4c6a-9154-be506a000fbe)

**Comment by kkoreilly** [comment]
This happens when you change anything in device settings, so the issue is that it can not correctly detect whether the `KeyMap` and `KeyMaps` are non-default.

**Comment by rcoreilly** [comment]
this just bit me in the latest update..

**Comment by kkoreilly** [comment]
I fixed this in f293200860f11ace9e60a6eeb98f01a3ee0dff54.
