### ISSUE TITLE
demo stuck and unresponsive when double click on title bar of the window 

### ISSUE THREAD

**Issue by c1ngular** [cogentcore/core#915]
### Describe the bug

just build and run demo , double click on window title bar cause app unresponsive  on Apple M1 Pro Sonoma 14.2.1 

### How to reproduce

just build and run demo , double click on window title bar

### Platform

macOS

**Comment by kkoreilly** [comment]
I can not reproduce this issue on my Apple M1 Max MacBook Pro on Sonoma 14.2.1. When I double click on the window title bar, it makes the window take up the entire screen as expected, and it does not make the app unresponsive. Are you using go 1.21 and the latest version of Cogent Core? Does this also happen when running the `hello` example? What version of the Vulkan SDK do you have installed? (See the `Vulkan Instance Version` at the top of `vulkaninfo --summary`) Does this also happen when you resize the window by dragging on the edge? What about when you press the green fullscreen button?

**Comment by kkoreilly** [comment]
The cause of this is probably your Vulkan SDK version; can you try installing version 1.3.261.1 of the Vulkan SDK? (see #644)

**Comment by c1ngular** [comment]
@kkoreilly 
i just cloned the repository and tried again , it still happens , hello example as well . 
when i double clicked window's title bar , i can see it tries to maximize the window (window size enlarge a little bit then got stuck ) . 
i am using Vulkan SDK version : 1.3.275.0 , go version : go1.21.1 

i also spotted some inconsistent with segmented button outline : 
<img width="510" alt="截屏2024-02-28 15 18 09" src="https://github.com/cogentcore/core/assets/9145844/70380213-c27e-40dc-a7df-245976f9199e">

P.S. good job , this is the most elegant and beautiful golang UI framework i have ever seen so far  , keep up good work .

**Comment by rcoreilly** [comment]
Yeah the latest 1.3.275 version of vulkan seems to be causing this hang -- haven't had a chance to investigate yet.  Try installing the 261.1 version (look in the older releases) -- that definitely works!

**Comment by kkoreilly** [comment]
Yep, the problem is definitely the version of the Vulkan SDK. I have updated the documentation to have the correct install command: you should now run `curl -O https://sdk.lunarg.com/sdk/download/1.3.261.1/mac/vulkansdk-macos-1.3.261.1.dmg` and then do the rest of the other install steps (run `open vulkansdk-macos-1.3.261.1.dmg` and double click `InstallVulkan.app`). Apologies for the out-of-date documentation!

**Comment by kkoreilly** [comment]
Also, I am planning to improve the Vulkan installation pathway at some point so that you don't have to install it manually.

**Comment by c1ngular** [comment]
@kkoreilly no rush , i am just exploring , not really doing anything with this at this moment

**Comment by kkoreilly** [comment]
Can you try the updated install commands I stated above?

> Yep, the problem is definitely the version of the Vulkan SDK. I have updated the documentation to have the correct install command: you should now run `curl -O https://sdk.lunarg.com/sdk/download/1.3.261.1/mac/vulkansdk-macos-1.3.261.1.dmg` and then do the rest of the other install steps (run `open vulkansdk-macos-1.3.261.1.dmg` and double click `InstallVulkan.app`). Apologies for the out-of-date documentation!

**Comment by kkoreilly** [comment]
I have stated the solution to this issue above, so I will close this issue. You can reopen it if you have any further issues after trying my solution, which I have also restated again below:

> Yep, the problem is definitely the version of the Vulkan SDK. I have updated the documentation to have the correct install command: you should now run `curl -O https://sdk.lunarg.com/sdk/download/1.3.261.1/mac/vulkansdk-macos-1.3.261.1.dmg` and then do the rest of the other install steps (run `open vulkansdk-macos-1.3.261.1.dmg` and double click `InstallVulkan.app`). Apologies for the out-of-date documentation!

**Comment by kkoreilly** [comment]
You can use the new `core setup` command now to easily install Vulkan (see the install documentation on the website).
