### ISSUE TITLE
How to set the title for NewSeparator, the ideal position is left-center-right

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#920]
### Describe the feature

see png

**Comment by ddkwork** [comment]
![{57DDB4F3-3862-453b-B2C1-FD27FABB74B1}.png](https://github.com/cogentcore/core/assets/19886504/1db934da-40a6-4a88-899a-82a5dc7868db)

**Comment by kkoreilly** [comment]
If you want text above the separator, you can just add it with `gi.NewLabel`.

**Comment by ddkwork** [comment]
Thank you, working



---Original---
From: ***@***.***&gt;
Date: Thu, Feb 29, 2024 23:45 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cogentcore/core] How to set the title for NewSeparator, theideal position is left-center-right (Issue #920)




 
If you want text above the separator, you can just add it with gi.NewLabel.
