### ISSUE TITLE
core generate err

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#930]
### Describe the bug

 programmer error: grease: two fields were assigned the same name

### How to reproduce

cd to giv dir,then run command "core generate" get this err "programmer error: grease: two fields were assigned the same name", last the core is exit(1)

### Example code

```go
if nbase == obase {
					slog.Error("programmer error: grease: two fields were assigned the same name", "name", name, "field0", of.Name, "field1", nf.Name)
```

### Relevant output

```shell
core exit with 1
```

### Platform

Windows

**Comment by kkoreilly** [comment]
I can not reproduce this. Please tell me which fields it says have the same name; what is the exact output of the program? Also, do you have the latest version of the `core` tool installed (run `go install ./core` in the root of this repository).

**Comment by ddkwork** [comment]
all thing is latest




2762713521
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cogentcore/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cogentcore/core] core generate err (Issue #930)





 
I can not reproduce this. Please tell me which fields it says have the same name; what is the exact output of the program? Also, do you have the latest version of the core tool installed (run go install ./core in the root of this repository).

**Comment by kkoreilly** [comment]
> Please tell me which fields it says have the same name; what is the exact output of the program?

**Comment by ddkwork** [comment]
Generally I get any errors and exceptions I refresh the latest commits have been tested in various ways, I have done it in both the core directory and the giv directory



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 12:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
I can not reproduce this. Please tell me which fields it says have the same name; what is the exact output of the program? Also, do you have the latest version of the core tool installed (run go install ./core in the root of this repository).

**Comment by kkoreilly** [comment]
The error messages prints *which* fields have the same name. I am asking *which* fields have the same name. Can you please copy and paste the exact error message that the program prints?

**Comment by ddkwork** [comment]
This is the full information of the output of your code call slog.error, to see what exactly the name is will have to wait for me to debug



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 13:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
The error messages prints which fields have the same name. I am asking which fields have the same name. Can you please copy and paste the exact error message that the program prints?

**Comment by kkoreilly** [comment]
I do not understand. The following code should print the names of the conflicting fields:

```go
if nbase == obase {
    slog.Error("programmer error: grease: two fields were assigned the same name", "name", name, "field0", of.Name, "field1", nf.Name)
```

**Comment by ddkwork** [comment]
The duplicate name field shown in the log is Generate.Gtigen, since core doesn't have unit tests, I can't see the specific context by debugging, I'm going to try to make unit tests to debug it



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 13:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
I do not understand. The following code should print the names of the conflicting fields:
 if nbase == obase {     slog.Error("programmer error: grease: two fields were assigned the same name", "name", name, "field0", of.Name, "field1", nf.Name)

**Comment by ddkwork** [comment]
Or to quickly confirm if it's a bug, you can anydesk me, I remember a long time ago I could run core commands on my computer without errors, and recently I couldn't use it because of this warning log




2762713521
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cogentcore/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cogentcore/core] core generate err (Issue #930)





 
I can not reproduce this. Please tell me which fields it says have the same name; what is the exact output of the program? Also, do you have the latest version of the core tool installed (run go install ./core in the root of this repository).

**Comment by kkoreilly** [comment]
I am available to debug this on your computer now.

**Comment by kkoreilly** [comment]
Never mind, I can reproduce the issue on my computer now. I will debug this on my computer.

**Comment by ddkwork** [comment]
1670379990



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 13:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
I am available to debug this on your computer now.

**Comment by ddkwork** [comment]
sure?



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 13:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
Never mind, I can reproduce the issue on my computer now. I will debug this on my computer.

**Comment by kkoreilly** [comment]
Yep, I don't need to debug it on your computer if I can reproduce the issue on mine.

**Comment by ddkwork** [comment]
ok



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 8, 2024 13:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] core generate err (Issue #930)




 
Yep, I don't need to debug it on your computer if I can reproduce the issue on mine.

**Comment by ddkwork** [comment]
func TestName(t *testing.T) {
    mylog.Error(os.Chdir("../giv"))
    opts := grease.DefaultOptions("Cogent Core", "Command line tools for developing apps and libraries using the Cogent Core framework.")
    opts.DefaultFiles = []string{"core.toml"}
    opts.SearchUp = true
    grease.Run(opts, &amp;config.Config{}, cmd.Build, cmd.Run, cmd.Pack, cmd.Install, generate.Generate, cmd.Changed, cmd.Pull, cmd.Log, cmd.Release, cmd.NextRelease)
}






2762713521
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cogentcore/core"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cogentcore/core] core generate err (Issue #930)





 
Yep, I don't need to debug it on your computer if I can reproduce the issue on mine.

**Comment by ddkwork** [comment]
oh no 
<img width="1280" alt="{8575750D-B273-4a19-82FA-52A7957C17FC}" src="https://github.com/cogentcore/core/assets/19886504/9a7462fc-8d7a-40fa-86bb-9463fe1ac881">

**Comment by kkoreilly** [comment]
You should be able to access it somehow. It is just the `coverage.html` file in `github.com/cogentcore/core.wiki`.

**Comment by ddkwork** [comment]
<img width="1280" alt="{740C0A32-536E-4273-B499-29AC278E89F7}" src="https://github.com/cogentcore/core/assets/19886504/431166bd-2cee-4996-ac33-8a75b7549b6e">

**Comment by kkoreilly** [comment]
You can't see it on the github website, since they hide wiki repos. You need to clone it on your computer with that URL and then pull the HTML file up in your browser.

**Comment by ddkwork** [comment]
<img width="1280" alt="{FE565D94-291A-4fd1-A3F3-2FB20BBE7EF8}" src="https://github.com/cogentcore/core/assets/19886504/fddec2f5-7b38-4b92-95d4-7ea3636df0f3">
<img width="1280" alt="{34BD3E4A-85BE-4d08-9019-E622DE7829C1}" src="https://github.com/cogentcore/core/assets/19886504/e22a2e5e-8ca2-4f1f-84fe-8fbb0aa2b956">

**Comment by kkoreilly** [comment]
The wiki is hidden on GitHub. You need to clone the `github.com/cogentcore/core.wiki` repository locally and open the `coverage.html` file in it. Alternatively, I can just send you the file if you want, but it won't stay up-to-date.

**Comment by ddkwork** [comment]
<img width="1280" alt="{E597F6D1-5FAF-43c1-8BAA-457A44388552}" src="https://github.com/cogentcore/core/assets/19886504/48f05a09-893d-4843-8864-2926421b128f">

**Comment by ddkwork** [comment]
> Wiki 在 GitHub 上是隐藏的。您需要在本地克隆存储库并打开其中的文件。或者，如果您愿意，我可以将文件发送给您，但它不会保持最新状态。`github.com/cogentcore/core.wiki``coverage.html`

send to me please

**Comment by ddkwork** [comment]
this can be debug
```go
package main

import (
	"cogentcore.org/core/core/cmd"
	"cogentcore.org/core/core/config"
	"cogentcore.org/core/core/generate"
	"cogentcore.org/core/grease"
	"cogentcore.org/core/mylog"
	"os"
	"testing"
)

func TestName(t *testing.T) {
	mylog.Error(os.Chdir("../giv"))
	os.Args = []string{
		"",
		"generate",
	}
	opts := grease.DefaultOptions("Cogent Core", "Command line tools for developing apps and libraries using the Cogent Core framework.")
	opts.DefaultFiles = []string{"core.toml"}
	opts.SearchUp = true
	grease.Run(opts, &config.Config{}, cmd.Build, cmd.Run, cmd.Pack, cmd.Install, generate.Generate, cmd.Changed, cmd.Pull, cmd.Log, cmd.Release, cmd.NextRelease)
}
```

**Comment by kkoreilly** [comment]
Try downloading this file, renaming it to `coverage.html` (GitHub doesn't support sending HTML files), and then opening it in your browser.

[coverage.txt](https://github.com/cogentcore/core/files/14533990/coverage.txt)
