### ISSUE TITLE
clipboard  error

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#934]
### Describe the bug

Windows copy any content to the clipboard and paste it into the text editor box will not take effect immediately, you have to press any key in the editor box to fill in the value.

### How to reproduce

   ![image](https://github.com/cogentcore/core/assets/19886504/4b236bee-e745-491a-8315-f862bf1b0ad4)

### Platform

Windows

**Comment by ddkwork** [comment]
I forgot to mention that I ctrl+v pasted, so I guess I didn't register this shortcut combination to the text editor's event list.

**Comment by kkoreilly** [comment]
I can reproduce this on multiple platforms and will work on fixing it.
