### ISSUE TITLE
TableView can not set struct

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/core#938]
### Describe the bug

see title

### How to reproduce

go run https://github.com/cogentcore/cogent/blob/main/ai%2Fai.go#L47-L47

### Platform

Windows

**Comment by ddkwork** [comment]
https://github.com/cogentcore/cogent/blob/main/ai%2Fai.go#L54-L54

**Comment by kkoreilly** [comment]
A `TableView` is designed to represent a slice of structs, not a single struct. If you want to represent a single struct, use a `StructView`. If you want to initialize the `TableView` with one struct, make a slice (`SetSlice(&[]Model{ModelJSON})`).

**Comment by ddkwork** [comment]
Ok, the main functions have been completed, and the others are doc, about, etc., which can be done in the later stage. Now the main thing is that the interface is not ideal, I hope you will make it beautiful as soon as possible



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 18, 2024 01:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/core] TableView can not set struct (Issue #938)




 
A TableView is designed to represent a slice of structs, not a single struct. If you want to represent a single struct, use a StructView. If you want to initialize the TableView with one struct, make a slice (SetSlice(&amp;[]Model{ModelJSON})).

**Comment by kkoreilly** [comment]
I will work on improving the interface as soon as I have time.

**Comment by kkoreilly** [comment]
Can you try to pull before you make changes and not overwrite my changes when there is a merge conflict? You accidentally got rid of some changes I made earlier today. Thanks!

**Comment by ddkwork** [comment]
I'm sorry, this morning I merged the commit like this: fetch xxx I chose to merge instead of rebase, at this point goland doesn't show any conflicting prompts, can you tell me that the changes to the ai directory are missing? or other directories



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 18, 2024 04:50 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cogentcore/core] TableView can not set struct (Issue #938)




 
Can you try to pull before you make changes and not overwrite my changes when there is a merge conflict? You accidentally got rid of some changes I made earlier today. Thanks!

**Comment by kkoreilly** [comment]
No worries, I was able to finish and reapply my changes later; just make sure to pull and rebase in the future.

**Comment by ddkwork** [comment]
To make sure of this, when I update your commit, I should check your commit first, and then rebase it every time after that, so that your changes should be refreshed regardless of whether Goland prompts me to merge or rebase. I think it's a viable option, don't you think? It's puzzling that Goland didn't detect the conflict



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 18, 2024 07:26 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cogentcore/core] TableView can not set struct (Issue #938)




 
No worries, I was able to finish and reapply my changes later; just make sure to pull and rebase in the future.

**Comment by kkoreilly** [comment]
Yep, you should always pull and rebase when possible.
