### ISSUE TITLE
Error accessing to the fonts in girl/paint.FontLib

### ISSUE THREAD

**Issue by Tom5521** [cogentcore/core#943]
### Describe the bug

Just try to run the hello world example and I get this error, by the way, I'm on linux.

### How to reproduce

Trying to make the documentation hello world

### Example code

```go
package main

import (
	"cogentcore.org/core/gi"
)

func main() {
	b := gi.NewBody("Hi")
	gi.NewButton(b).SetText("Hello World!")
	b.RunMainWindow()
}
```

### Relevant output

```shell
2024/03/20 17:48:56 ERROR girl/paint.FontLib: error accessing path path=. err=stat .: no such file or directory
2024/03/20 17:48:56 ERROR girl/paint.FontLib: error walking path path=/usr/share/fonts/truetype err=stat .: no such file or directory
```

### Platform

Linux

**Comment by Tom5521** [comment]
I solved it by making a `sudo ln -s /usr/share/fonts/TTF/ /usr/share/fonts/truetype`

Either way, I think that's something that needs to be fixed.

**Comment by kkoreilly** [comment]
Indeed, this should not happen. What distro of linux are you using? From some quick searching, it seems like most distros of linux store their fonts in `/usr/share/fonts/truetype`. Regardless, I will add support for finding fonts in `/usr/share/fonts/TTF`.

**Comment by Tom5521** [comment]
>  What distro of linux are you using?

I'm using Arch Linux

**Comment by kkoreilly** [comment]
I implemented a fix for this in the commit above; can you remove your symlink, update to the latest version of Cogent Core (`go get cogentcore.org/core@a33095d`), and ensure that the error does not happen again?

**Comment by Tom5521** [comment]
The error no longer occurs, now it works correctly, thank you.
