### ISSUE TITLE
Use libmpv instead of libav for video

### ISSUE THREAD

**Issue by yxxyun** [cogentcore/core#950]
### Describe the feature

libmpv is more geared towards building applications with advanced media playback capabilities

**Comment by kkoreilly** [comment]
Is there any Go library for interacting with libmpv? If so, I would be interested in using it.

**Comment by yxxyun** [comment]
https://github.com/gen2brain/go-mpv  
https://github.com/aynakeya/go-mpv

**Comment by kkoreilly** [comment]
Those packages look relatively promising; I will take a deeper look at this soon. Thanks!

**Comment by c1ngular** [comment]
I don't think those two are ready to be used as customizable video player , They are just interacting with MPV player instance .

**Comment by rcoreilly** [comment]
linking to original issue: #516
