### ISSUE TITLE
blur render in std box is not clearing properly, for transparent background case, i.e., with dialogs, menus etc.

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#952]
### Describe the bug

scrolling menus or moving popups around: blur is additive and gets darker and darker.

### How to reproduce

popup dialog, move it, or scroll a menu

### Platform

macOS

**Comment by kkoreilly** [comment]
Also probably happened around the big renaming PR.

**Comment by rcoreilly** [comment]
it happend in f2efc6e3b relative to prior 8b4e0546e
