### ISSUE TITLE
vulkansdk-macos-1.3.261.1.dmg left around on disk

### ISSUE THREAD

**Issue by gedw99** [cogentcore/core#965]
### Describe the bug

```sh

core setup

```

this runs perfectly fine, but leaves the vulkansdk-macos-1.3.261.1.dmg on disk 

just need to remember to delete if the install succeeds.

I thought that maybe its left around because then you would check for it and then not curl it again, but thats not the case.

The other fix is for the core system to have its own dedicated file cache but thats maybe not really needed.

### How to reproduce

```sh

core setup

```

### Platform

macOS

**Comment by kkoreilly** [comment]
Yep, I will try to have it delete it. I thought I might have tried to delete it before and there was some issue with ejecting it properly, but this should be doable.

**Comment by gedw99** [comment]
Ah yes  it needs to be mounted since it’s a dmg, and hence ejected afterwards.

Will leave this issue open.

**Comment by kkoreilly** [comment]
This is no longer relevant since we switched over to WebGPU (#507).
