### ISSUE TITLE
crash log path should decode spaces ?

### ISSUE THREAD

**Issue by gedw99** [cogentcore/core#966]
### Describe the bug

```sh
----- END OF STACK TRACE -----
2024/05/19 12:15:03 SAVED CRASH LOG TO /Users/apple/Library/Plot View/crash-logs/crash_2024-05-19_12-15-03

```

The actual path needs tube "escaped" to allow for the way spaces are done for folders in MAC OS, and perhaps other OS too.
Correct output is:
```sh
/Users/apple/Library/Plot\ View/crash-logs/crash_2024-05-19_12-15-03
```

### How to reproduce

I got this running the Plotview demo.

### Platform

macOS

**Comment by kkoreilly** [comment]
Yep, I will work on implementing this soon. Thanks for reporting this!

**Comment by kkoreilly** [comment]
Also, I am in the middle of a major rewrite of our widget configuration structure (see the [tree branch](https://github.com/cogentcore/core/tree/tree)), so it may take a little longer than usual for this to be fixed on the main branch.

**Comment by gedw99** [comment]
No worries. Thanks for letting me know…

will leave it open as an issue

**Comment by kkoreilly** [comment]
Apologies for the delayed fix; I just finished (almost all of) the major refactoring I was working on. It should be working now; please let me know if you have any other issues.
