### ISSUE TITLE
core example: basic: link error

### ISSUE THREAD

**Issue by susugagalala** [cogentcore/core#969]
### Describe the bug

basic hello world example in examples folder of core linkage error: ld: library not found for -lMoltenVK

### How to reproduce

go to: examples/basic folder of core
run: go build

### Platform

macOS

**Comment by kkoreilly** [comment]
As stated on the [Cogent Core website](https://cogentcore.org/core/getting-started/install), to develop Cogent Core apps, you must install the Cogent Core tool and then run `core setup` to install necessary platform specific dependencies.

**Comment by kkoreilly** [comment]
My comment above resolves this issue, so I will close this. Please let me know if you have any other problems.
