### ISSUE TITLE
fix lots of bad cases from radius fix

### ISSUE THREAD

**Issue by rcoreilly** [cogentcore/core#989]
### Describe the bug

dialog buttons, file picker rows are a couple of obvious ones.  generally dialogs not doing well.

will add limits on going up stack, along with other constraints on size probably.

### How to reproduce

demo ,etc

### Platform

macOS

**Comment by kkoreilly** [comment]
(This resulted from #660).

**Comment by rcoreilly** [comment]
Fixed with 7dea1c36c and e82cf36ca
